{
  "version": "4.16.6",
  "time": 0.255,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "fl_convenio_entrada_interv",
        "title": "Convênio Entrada Interveniente",
        "path": "data/fl_convenio_entrada_interv.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_convenio",
              "title": "Convênio de Entrada - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_interveniente",
              "title": "Interveniente - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_convenio"
              ],
              "reference": {
                "fields": [
                  "id_convenio"
                ],
                "resource": "dm_convenio_entrada"
              }
            },
            {
              "fields": [
                "id_interveniente"
              ],
              "reference": {
                "fields": [
                  "id_interveniente"
                ],
                "resource": "dm_interveniente_conv_ent"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "fl_convenio_entrada_interv"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "372ea6bbb4d6d471a4ee9fa870f601fc",
          "bytes": 1691,
          "fields": 2,
          "rows": 539
        }
      },
      "time": 0.255,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 1,
          "rowPosition": 2,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 13,
          "rowPosition": 14,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"14\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 32,
          "rowPosition": 33,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"33\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 35,
          "rowPosition": 36,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"36\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 44,
          "rowPosition": 45,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"45\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 49,
          "rowPosition": 50,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"50\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 53,
          "rowPosition": 54,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"54\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 67,
          "rowPosition": 68,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"68\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 91,
          "rowPosition": 92,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"92\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 98,
          "rowPosition": 99,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"99\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 99,
          "rowPosition": 100,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"100\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 101,
          "rowPosition": 102,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"102\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 105,
          "rowPosition": 106,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"106\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 109,
          "rowPosition": 110,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"110\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 112,
          "rowPosition": 113,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"113\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 115,
          "rowPosition": 116,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"116\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 117,
          "rowPosition": 118,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"118\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 140,
          "rowPosition": 141,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"141\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 143,
          "rowPosition": 144,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"144\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 145,
          "rowPosition": 146,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"146\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 153,
          "rowPosition": 154,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"154\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 159,
          "rowPosition": 160,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"160\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 160,
          "rowPosition": 161,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"161\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 173,
          "rowPosition": 174,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"174\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 174,
          "rowPosition": 175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"175\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 179,
          "rowPosition": 180,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"180\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 182,
          "rowPosition": 183,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"183\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 191,
          "rowPosition": 192,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"192\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 192,
          "rowPosition": 193,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"193\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 202,
          "rowPosition": 203,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"203\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 205,
          "rowPosition": 206,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"206\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 218,
          "rowPosition": 219,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"219\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 230,
          "rowPosition": 231,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"231\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 232,
          "rowPosition": 233,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"233\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 233,
          "rowPosition": 234,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"234\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 240,
          "rowPosition": 241,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"241\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 241,
          "rowPosition": 242,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"242\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 257,
          "rowPosition": 258,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"258\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 258,
          "rowPosition": 259,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"259\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 264,
          "rowPosition": 265,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"265\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 265,
          "rowPosition": 266,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"266\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 269,
          "rowPosition": 270,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"270\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 271,
          "rowPosition": 272,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"272\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 285,
          "rowPosition": 286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"286\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 300,
          "rowPosition": 301,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"301\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 302,
          "rowPosition": 303,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"303\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 305,
          "rowPosition": 306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"306\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 306,
          "rowPosition": 307,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"307\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 310,
          "rowPosition": 311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"311\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 317,
          "rowPosition": 318,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"318\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 321,
          "rowPosition": 322,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"322\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 327,
          "rowPosition": 328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"328\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 345,
          "rowPosition": 346,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"346\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 346,
          "rowPosition": 347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"347\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 366,
          "rowPosition": 367,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"367\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 367,
          "rowPosition": 368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"368\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 368,
          "rowPosition": 369,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"369\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 384,
          "rowPosition": 385,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"385\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 385,
          "rowPosition": 386,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"386\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 390,
          "rowPosition": 391,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"391\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 408,
          "rowPosition": 409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"409\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 411,
          "rowPosition": 412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"412\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 420,
          "rowPosition": 421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"421\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 427,
          "rowPosition": 428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"428\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 433,
          "rowPosition": 434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"434\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 438,
          "rowPosition": 439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"439\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 441,
          "rowPosition": 442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"442\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 442,
          "rowPosition": 443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"443\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 447,
          "rowPosition": 448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"448\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 456,
          "rowPosition": 457,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"457\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 473,
          "rowPosition": 474,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"474\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 479,
          "rowPosition": 480,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"480\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 484,
          "rowPosition": 485,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"485\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 509,
          "rowPosition": 510,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"510\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 510,
          "rowPosition": 511,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"511\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 511,
          "rowPosition": 512,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"512\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 512,
          "rowPosition": 513,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"513\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 513,
          "rowPosition": 514,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"514\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 517,
          "rowPosition": 518,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"518\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 520,
          "rowPosition": 521,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"521\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 523,
          "rowPosition": 524,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"524\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 524,
          "rowPosition": 525,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"525\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 525,
          "rowPosition": 526,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"526\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 526,
          "rowPosition": 527,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"527\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 529,
          "rowPosition": 530,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"530\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 532,
          "rowPosition": 533,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"533\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "id_interveniente"
          ],
          "rowNumber": 534,
          "rowPosition": 535,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"535\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 87
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 87,
    "tasks": 1
  },
  "valid": false
}