{
  "version": "4.38.0",
  "time": 412.827,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "0cc7a74235722238e17e61263d4ff1c6",
          "bytes": 58446363,
          "fields": 27,
          "rows": 1918566
        }
      },
      "time": 412.827,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44417",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "419",
            "28662",
            "1",
            "51",
            "75",
            "12410",
            "120792",
            "384172",
            "79177",
            "889",
            "1831642",
            "2670",
            "2925",
            "2022",
            "2022-12-14",
            "0.0000",
            "85200.0000",
            "85200.00",
            "53000.0000",
            "53000.00",
            "53000.00"
          ],
          "rowNumber": 1820855,
          "rowPosition": 1820856,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820856\" violates the foreign key: for \"id_contrato\": values \"79177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20416",
            "1",
            "26",
            "818",
            "15250",
            "149442",
            "383326",
            "79175",
            "980",
            "1831233",
            "2863",
            "2925",
            "2022",
            "2022-12-01",
            "1800.0000",
            "2.8000",
            "5040.00",
            "2.4800",
            "4464.00",
            "4464.00"
          ],
          "rowNumber": 1864371,
          "rowPosition": 1864372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1864372\" violates the foreign key: for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20416",
            "1",
            "26",
            "818",
            "15250",
            "149442",
            "383326",
            "79175",
            "980",
            "1831233",
            "2863",
            "2925",
            "2022",
            "2022-12-01",
            "1200.0000",
            "2.8000",
            "3360.00",
            "2.4800",
            "2976.00",
            "2976.00"
          ],
          "rowNumber": 1864397,
          "rowPosition": 1864398,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1864398\" violates the foreign key: for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20416",
            "1",
            "26",
            "818",
            "15250",
            "149442",
            "383326",
            "79175",
            "980",
            "1831233",
            "2863",
            "2925",
            "2022",
            "2022-12-01",
            "7200.0000",
            "2.8000",
            "20160.00",
            "2.4800",
            "17856.00",
            "17856.00"
          ],
          "rowNumber": 1865307,
          "rowPosition": 1865308,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1865308\" violates the foreign key: for \"id_contrato\": values \"79175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "248",
            "72320",
            "1",
            "54",
            "119",
            "7611",
            "200656",
            "385219",
            "79178",
            "889",
            "1831296",
            "2944",
            "2270",
            "2022",
            "2022-12-27",
            "65.0000",
            "1683.3300",
            "109416.45",
            "946.1500",
            "61499.75",
            "61499.75"
          ],
          "rowNumber": 1915264,
          "rowPosition": 1915265,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915265\" violates the foreign key: for \"id_contrato\": values \"79178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "62",
            "518",
            "615",
            "19942",
            "385511",
            "79180",
            "237",
            "1831957",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "50.0000",
            "13.6000",
            "680.00",
            "9.5000",
            "475.00",
            "475.00"
          ],
          "rowNumber": 1916241,
          "rowPosition": 1916242,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916242\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "44",
            "102",
            "624",
            "49534",
            "385511",
            "79180",
            "889",
            "1831992",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "50.0000",
            "13.0000",
            "650.00",
            "13.0000",
            "650.00",
            "650.00"
          ],
          "rowNumber": 1916244,
          "rowPosition": 1916245,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916245\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "44",
            "629",
            "7806",
            "75197",
            "385511",
            "79180",
            "889",
            "1831992",
            "2540",
            "2081",
            "2022",
            "2022-12-28",
            "500.0000",
            "13.0000",
            "6500.00",
            "9.5000",
            "4750.00",
            "4750.00"
          ],
          "rowNumber": 1916245,
          "rowPosition": 1916246,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916246\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "44",
            "629",
            "7949",
            "125712",
            "385511",
            "79180",
            "889",
            "1831992",
            "2540",
            "2081",
            "2022",
            "2022-12-28",
            "450.0000",
            "5.2000",
            "2340.00",
            "5.2000",
            "2340.00",
            "2340.00"
          ],
          "rowNumber": 1916246,
          "rowPosition": 1916247,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916247\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "44",
            "629",
            "7949",
            "68441",
            "385511",
            "79180",
            "889",
            "1831992",
            "2540",
            "2081",
            "2022",
            "2022-12-28",
            "300.0000",
            "11.0000",
            "3300.00",
            "11.0000",
            "3300.00",
            "3300.00"
          ],
          "rowNumber": 1916247,
          "rowPosition": 1916248,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916248\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "44",
            "102",
            "13182",
            "32845",
            "385511",
            "79180",
            "889",
            "1831992",
            "2540",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "11.8200",
            "2364.00",
            "11.8200",
            "2364.00",
            "2364.00"
          ],
          "rowNumber": 1916248,
          "rowPosition": 1916249,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916249\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "55",
            "731",
            "10686",
            "30478",
            "385511",
            "79180",
            "889",
            "1831986",
            "2541",
            "2081",
            "2022",
            "2022-12-28",
            "4.0000",
            "19.0000",
            "76.00",
            "24.0000",
            "96.00",
            "96.00"
          ],
          "rowNumber": 1916249,
          "rowPosition": 1916250,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916250\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "55",
            "731",
            "13607",
            "10788",
            "385511",
            "79180",
            "889",
            "1831986",
            "2541",
            "2081",
            "2022",
            "2022-12-28",
            "4.0000",
            "52.9000",
            "211.60",
            "52.9000",
            "211.60",
            "211.60"
          ],
          "rowNumber": 1916250,
          "rowPosition": 1916251,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916251\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "11120",
            "81908",
            "385511",
            "79180",
            "1331",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "23.0000",
            "460.00",
            "23.0000",
            "460.00",
            "460.00"
          ],
          "rowNumber": 1916251,
          "rowPosition": 1916252,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916252\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "334",
            "39174",
            "385511",
            "79180",
            "131",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "20.9000",
            "2090.00",
            "20.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1916252,
          "rowPosition": 1916253,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916253\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "334",
            "76643",
            "385511",
            "79180",
            "131",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "31.0000",
            "930.00",
            "31.0000",
            "930.00",
            "930.00"
          ],
          "rowNumber": 1916309,
          "rowPosition": 1916310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916310\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "314",
            "481",
            "13156",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "57.0000",
            "5700.00",
            "57.0000",
            "5700.00",
            "5700.00"
          ],
          "rowNumber": 1916310,
          "rowPosition": 1916311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916311\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "759",
            "422",
            "336644",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "1000.0000",
            "0.4000",
            "400.00",
            "0.3000",
            "300.00",
            "300.00"
          ],
          "rowNumber": 1916311,
          "rowPosition": 1916312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916312\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "759",
            "422",
            "200756",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "1000.0000",
            "0.4000",
            "400.00",
            "0.4000",
            "400.00",
            "400.00"
          ],
          "rowNumber": 1916312,
          "rowPosition": 1916313,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916313\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "61",
            "619",
            "15706",
            "51050",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "22.0000",
            "440.00",
            "22.0000",
            "440.00",
            "440.00"
          ],
          "rowNumber": 1916313,
          "rowPosition": 1916314,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916314\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "323",
            "16290",
            "313649",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "24.8800",
            "497.60",
            "24.8800",
            "497.60",
            "497.60"
          ],
          "rowNumber": 1916314,
          "rowPosition": 1916315,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916315\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "61",
            "619",
            "392",
            "82586",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "300.0000",
            "249.0000",
            "74700.00",
            "237.5000",
            "71250.00",
            "71250.00"
          ],
          "rowNumber": 1916315,
          "rowPosition": 1916316,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916316\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "744",
            "10981",
            "221070",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "300.0000",
            "3.4900",
            "1047.00",
            "3.4900",
            "1047.00",
            "1047.00"
          ],
          "rowNumber": 1916316,
          "rowPosition": 1916317,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916317\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "61",
            "619",
            "3961",
            "58028",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "300.0000",
            "10.0000",
            "3000.00",
            "10.0000",
            "3000.00",
            "3000.00"
          ],
          "rowNumber": 1916317,
          "rowPosition": 1916318,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916318\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "480",
            "113460",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "51.4700",
            "1029.40",
            "51.4700",
            "1029.40",
            "1029.40"
          ],
          "rowNumber": 1916318,
          "rowPosition": 1916319,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916319\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "425",
            "324",
            "46746",
            "385511",
            "79180",
            "1331",
            "1831958",
            "2926",
            "2081",
            "2022",
            "2022-12-28",
            "5.0000",
            "23.0000",
            "115.00",
            "23.0000",
            "115.00",
            "115.00"
          ],
          "rowNumber": 1916319,
          "rowPosition": 1916320,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916320\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "480",
            "157653",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "247.0000",
            "2470.00",
            "247.0000",
            "2470.00",
            "2470.00"
          ],
          "rowNumber": 1916320,
          "rowPosition": 1916321,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916321\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "480",
            "70900",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "2.0000",
            "130.0000",
            "260.00",
            "130.0000",
            "260.00",
            "260.00"
          ],
          "rowNumber": 1916321,
          "rowPosition": 1916322,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916322\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "32",
            "219",
            "18370",
            "242",
            "385511",
            "79180",
            "889",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "40.0000",
            "22.9000",
            "916.00",
            "22.9000",
            "916.00",
            "916.00"
          ],
          "rowNumber": 1916322,
          "rowPosition": 1916323,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916323\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "41",
            "7476",
            "133109",
            "385511",
            "79180",
            "889",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "40.0000",
            "31.0000",
            "1240.00",
            "31.0000",
            "1240.00",
            "1240.00"
          ],
          "rowNumber": 1916323,
          "rowPosition": 1916324,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916324\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "737",
            "5171",
            "162132",
            "385511",
            "79180",
            "889",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "8.0000",
            "1600.00",
            "8.0000",
            "1600.00",
            "1600.00"
          ],
          "rowNumber": 1916324,
          "rowPosition": 1916325,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916325\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "41",
            "16309",
            "14641",
            "385511",
            "79180",
            "889",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "13.0000",
            "390.00",
            "9.5000",
            "285.00",
            "285.00"
          ],
          "rowNumber": 1916325,
          "rowPosition": 1916326,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916326\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "76",
            "769",
            "823",
            "19721",
            "385511",
            "79180",
            "261",
            "1831975",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "29.0000",
            "580.00",
            "23.7500",
            "475.00",
            "475.00"
          ],
          "rowNumber": 1916326,
          "rowPosition": 1916327,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916327\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "323",
            "16044",
            "159803",
            "385511",
            "79180",
            "100",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "16.4000",
            "328.00",
            "16.4000",
            "328.00",
            "328.00"
          ],
          "rowNumber": 1916327,
          "rowPosition": 1916328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916328\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "323",
            "16044",
            "63102",
            "385511",
            "79180",
            "100",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "8.0000",
            "160.00",
            "16.4000",
            "328.00",
            "328.00"
          ],
          "rowNumber": 1916328,
          "rowPosition": 1916329,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916329\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "20",
            "245",
            "8531",
            "17070",
            "385511",
            "79180",
            "98",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "150.0000",
            "29.0000",
            "4350.00",
            "23.7500",
            "3562.50",
            "3562.50"
          ],
          "rowNumber": 1916329,
          "rowPosition": 1916330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916330\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "20",
            "245",
            "18591",
            "51746",
            "385511",
            "79180",
            "98",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "30.1000",
            "903.00",
            "30.0000",
            "900.00",
            "900.00"
          ],
          "rowNumber": 1916330,
          "rowPosition": 1916331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916331\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "16197",
            "16879",
            "385511",
            "79180",
            "594",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "40.0000",
            "159.0000",
            "6360.00",
            "152.0000",
            "6080.00",
            "6080.00"
          ],
          "rowNumber": 1916331,
          "rowPosition": 1916332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916332\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "18483",
            "115381",
            "385511",
            "79180",
            "594",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "35.0000",
            "169.0000",
            "5915.00",
            "171.0000",
            "5985.00",
            "5985.00"
          ],
          "rowNumber": 1916332,
          "rowPosition": 1916333,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916333\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "5309",
            "1995",
            "385511",
            "79180",
            "131",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "21.6500",
            "433.00",
            "19.0000",
            "380.00",
            "380.00"
          ],
          "rowNumber": 1916333,
          "rowPosition": 1916334,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916334\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "18445",
            "237370",
            "385511",
            "79180",
            "114",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "450.0000",
            "38.8000",
            "17460.00",
            "38.0000",
            "17100.00",
            "17100.00"
          ],
          "rowNumber": 1916334,
          "rowPosition": 1916335,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916335\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "37397",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "5.0000",
            "169.0000",
            "845.00",
            "114.0000",
            "570.00",
            "570.00"
          ],
          "rowNumber": 1916335,
          "rowPosition": 1916336,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916336\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "4463",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "5.0000",
            "120.0000",
            "600.00",
            "114.0000",
            "570.00",
            "570.00"
          ],
          "rowNumber": 1916336,
          "rowPosition": 1916337,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916337\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "83370",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "109.7100",
            "3291.30",
            "109.7100",
            "3291.30",
            "3291.30"
          ],
          "rowNumber": 1916337,
          "rowPosition": 1916338,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916338\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "7838",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "35.0000",
            "165.0000",
            "5775.00",
            "114.0000",
            "3990.00",
            "3990.00"
          ],
          "rowNumber": 1916338,
          "rowPosition": 1916339,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916339\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "127382",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "104.0000",
            "1040.00",
            "104.0000",
            "1040.00",
            "1040.00"
          ],
          "rowNumber": 1916339,
          "rowPosition": 1916340,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916340\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "37606",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "40.0000",
            "169.0000",
            "6760.00",
            "114.0000",
            "4560.00",
            "4560.00"
          ],
          "rowNumber": 1916340,
          "rowPosition": 1916341,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916341\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "13369",
            "118255",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "154.9700",
            "3099.40",
            "114.0000",
            "2280.00",
            "2280.00"
          ],
          "rowNumber": 1916341,
          "rowPosition": 1916342,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916342\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "25516",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "2.9000",
            "580.00",
            "0.9500",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1916342,
          "rowPosition": 1916343,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916343\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "6871",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "1.5000",
            "150.00",
            "0.9500",
            "95.00",
            "95.00"
          ],
          "rowNumber": 1916343,
          "rowPosition": 1916344,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916344\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "7641",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "1.5000",
            "150.00",
            "0.9500",
            "95.00",
            "95.00"
          ],
          "rowNumber": 1916344,
          "rowPosition": 1916345,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916345\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "49323",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "2.7000",
            "540.00",
            "2.7000",
            "540.00",
            "540.00"
          ],
          "rowNumber": 1916345,
          "rowPosition": 1916346,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916346\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "11824",
            "385511",
            "79180",
            "1022",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "1.5000",
            "150.00",
            "0.9500",
            "95.00",
            "95.00"
          ],
          "rowNumber": 1916346,
          "rowPosition": 1916347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916347\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "28696",
            "385511",
            "79180",
            "1022",
            "1831331",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "1.3900",
            "278.00",
            "0.9500",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1916347,
          "rowPosition": 1916348,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916348\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "647",
            "13462",
            "6279",
            "385511",
            "79180",
            "132",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "100.0000",
            "7.5000",
            "750.00",
            "7.5000",
            "750.00",
            "750.00"
          ],
          "rowNumber": 1916348,
          "rowPosition": 1916349,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916349\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "19",
            "330",
            "9881",
            "130095",
            "385511",
            "79180",
            "889",
            "1831993",
            "2540",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "40.0000",
            "400.00",
            "40.0000",
            "400.00",
            "400.00"
          ],
          "rowNumber": 1916349,
          "rowPosition": 1916350,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916350\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "26535",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "2.5000",
            "500.00",
            "2.5000",
            "500.00",
            "500.00"
          ],
          "rowNumber": 1916350,
          "rowPosition": 1916351,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916351\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "10202",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "1.5000",
            "300.00",
            "0.9500",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1916351,
          "rowPosition": 1916352,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916352\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "4",
            "16",
            "7801",
            "48550",
            "385511",
            "79180",
            "1022",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "200.0000",
            "1.5000",
            "300.00",
            "0.9500",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1916352,
          "rowPosition": 1916353,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916353\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "32",
            "100",
            "19412",
            "89075",
            "385511",
            "79180",
            "189",
            "1831400",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "21.5000",
            "645.00",
            "17.1000",
            "513.00",
            "513.00"
          ],
          "rowNumber": 1916353,
          "rowPosition": 1916354,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916354\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "15754",
            "7382",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "15.0000",
            "69.0000",
            "1035.00",
            "61.7500",
            "926.25",
            "926.25"
          ],
          "rowNumber": 1916354,
          "rowPosition": 1916355,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916355\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "2814",
            "237359",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "25.0000",
            "500.00",
            "19.0000",
            "380.00",
            "380.00"
          ],
          "rowNumber": 1916355,
          "rowPosition": 1916356,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916356\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "2814",
            "11404",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "15.0000",
            "150.00",
            "7.6000",
            "76.00",
            "76.00"
          ],
          "rowNumber": 1916356,
          "rowPosition": 1916357,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916357\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "2814",
            "3333",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "20.0000",
            "400.00",
            "11.4000",
            "228.00",
            "228.00"
          ],
          "rowNumber": 1916357,
          "rowPosition": 1916358,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916358\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "425",
            "14545",
            "55800",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "79.0000",
            "790.00",
            "79.0000",
            "790.00",
            "790.00"
          ],
          "rowNumber": 1916358,
          "rowPosition": 1916359,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916359\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "425",
            "14545",
            "131906",
            "385511",
            "79180",
            "190",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "5.0000",
            "35.0000",
            "175.00",
            "35.0000",
            "175.00",
            "175.00"
          ],
          "rowNumber": 1916359,
          "rowPosition": 1916360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916360\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "425",
            "647",
            "134523",
            "385511",
            "79180",
            "98",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "6.0000",
            "26.6000",
            "159.60",
            "26.6000",
            "159.60",
            "159.60"
          ],
          "rowNumber": 1916360,
          "rowPosition": 1916361,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916361\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "15814",
            "30813",
            "385511",
            "79180",
            "190",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "50.0000",
            "21.0000",
            "1050.00",
            "18.0000",
            "900.00",
            "900.00"
          ],
          "rowNumber": 1916361,
          "rowPosition": 1916362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916362\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "82",
            "744",
            "15775",
            "4193",
            "385511",
            "79180",
            "371",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "2.0000",
            "1.3800",
            "2.76",
            "1380.0000",
            "2760.00",
            "2760.00"
          ],
          "rowNumber": 1916362,
          "rowPosition": 1916363,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916363\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "50460",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "520.0000",
            "10400.00",
            "190.0000",
            "3800.00",
            "3800.00"
          ],
          "rowNumber": 1916363,
          "rowPosition": 1916364,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916364\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "9548",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "854.9900",
            "17099.80",
            "190.0000",
            "3800.00",
            "3800.00"
          ],
          "rowNumber": 1916364,
          "rowPosition": 1916365,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916365\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "142078",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "900.0000",
            "18000.00",
            "332.5000",
            "6650.00",
            "6650.00"
          ],
          "rowNumber": 1916365,
          "rowPosition": 1916366,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916366\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "4",
            "1831017",
            "12",
            "1",
            "1",
            "66",
            "27516",
            "1",
            "90",
            "355",
            "3037",
            "46614",
            "386032",
            "79179",
            "889",
            "1831954",
            "2735",
            "2842",
            "2022",
            "2023-01-07",
            "3000000.0000",
            "1.0000",
            "3000000.00",
            "1.0000",
            "3000000.00",
            "3000000.00"
          ],
          "rowNumber": 1916478,
          "rowPosition": 1916479,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916479\" violates the foreign key: for \"id_contrato\": values \"79179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "6872",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "500.0000",
            "10000.00",
            "190.0000",
            "3800.00",
            "3800.00"
          ],
          "rowNumber": 1916536,
          "rowPosition": 1916537,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916537\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "11075",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "799.0000",
            "15980.00",
            "285.0000",
            "5700.00",
            "5700.00"
          ],
          "rowNumber": 1916537,
          "rowPosition": 1916538,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916538\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "5188",
            "10408",
            "385511",
            "79180",
            "196",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "799.0000",
            "7990.00",
            "285.0000",
            "2850.00",
            "2850.00"
          ],
          "rowNumber": 1916538,
          "rowPosition": 1916539,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916539\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "153599",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "12.5000",
            "250.00",
            "12.5000",
            "250.00",
            "250.00"
          ],
          "rowNumber": 1916539,
          "rowPosition": 1916540,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916540\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "7124",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "18.0000",
            "180.00",
            "18.0000",
            "180.00",
            "180.00"
          ],
          "rowNumber": 1916540,
          "rowPosition": 1916541,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916541\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "26907",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "10.0000",
            "6.0000",
            "60.00",
            "4.7500",
            "47.50",
            "47.50"
          ],
          "rowNumber": 1916541,
          "rowPosition": 1916542,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916542\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "30398",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "8.0000",
            "160.00",
            "6.6500",
            "133.00",
            "133.00"
          ],
          "rowNumber": 1916542,
          "rowPosition": 1916543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916543\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "153227",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "3.0000",
            "60.00",
            "2.8500",
            "57.00",
            "57.00"
          ],
          "rowNumber": 1916543,
          "rowPosition": 1916544,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916544\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "57344",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "11.0000",
            "220.00",
            "11.0000",
            "220.00",
            "220.00"
          ],
          "rowNumber": 1916544,
          "rowPosition": 1916545,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916545\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "757",
            "15976",
            "154794",
            "385511",
            "79180",
            "889",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "20.0000",
            "10.0000",
            "200.00",
            "9.5000",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1916545,
          "rowPosition": 1916546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916546\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "52",
            "721",
            "7903",
            "1725",
            "385511",
            "79180",
            "184",
            "1831189",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "15.0000",
            "150.0000",
            "2250.00",
            "114.0000",
            "1710.00",
            "1710.00"
          ],
          "rowNumber": 1916546,
          "rowPosition": 1916547,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916547\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "20",
            "614",
            "3453",
            "29731",
            "385511",
            "79180",
            "889",
            "1831315",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "44.0000",
            "1320.00",
            "44.0000",
            "1320.00",
            "1320.00"
          ],
          "rowNumber": 1916548,
          "rowPosition": 1916549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916549\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "20",
            "614",
            "3453",
            "63109",
            "385511",
            "79180",
            "889",
            "1831315",
            "2658",
            "2081",
            "2022",
            "2022-12-28",
            "30.0000",
            "15.4000",
            "462.00",
            "15.4000",
            "462.00",
            "462.00"
          ],
          "rowNumber": 1916549,
          "rowPosition": 1916550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916550\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "49",
            "739",
            "16092",
            "28961",
            "385511",
            "79180",
            "237",
            "1831978",
            "2541",
            "2081",
            "2022",
            "2022-12-28",
            "50.0000",
            "4.5000",
            "225.00",
            "2.8500",
            "142.50",
            "142.50"
          ],
          "rowNumber": 1916551,
          "rowPosition": 1916552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916552\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "71909",
            "1",
            "64",
            "768",
            "5654",
            "58354",
            "385511",
            "79180",
            "889",
            "1831961",
            "2541",
            "2081",
            "2022",
            "2022-12-28",
            "50.0000",
            "19.5100",
            "975.50",
            "19.3100",
            "965.50",
            "965.50"
          ],
          "rowNumber": 1916552,
          "rowPosition": 1916553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916553\" violates the foreign key: for \"id_contrato\": values \"79180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "13",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "57492",
            "1",
            "77",
            "533",
            "1834",
            "92854",
            "386002",
            "79176",
            "889",
            "1831370",
            "2675",
            "1760",
            "2022",
            "2023-01-04",
            "0.0000",
            "414614.2600",
            "414614.26",
            "412708.3200",
            "412708.32",
            "412708.32"
          ],
          "rowNumber": 1916721,
          "rowPosition": 1916722,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916722\" violates the foreign key: for \"id_contrato\": values \"79176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43499",
            "13",
            "1831034",
            "21",
            "1",
            "1",
            "72",
            "57492",
            "1",
            "77",
            "533",
            "1834",
            "92854",
            "386014",
            "79181",
            "889",
            "1831370",
            "2675",
            "1760",
            "2022",
            "2023-01-05",
            "0.0000",
            "1277626.6400",
            "1277626.64",
            "1271697.6000",
            "1271697.60",
            "1271697.60"
          ],
          "rowNumber": 1918450,
          "rowPosition": 1918451,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918451\" violates the foreign key: for \"id_contrato\": values \"79181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 90
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 90,
    "tasks": 1
  },
  "valid": false
}