{
  "version": "4.16.6",
  "time": 2.855,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_convenio_entrada",
        "title": "Convênio Entrada - tabela fato",
        "path": "data/ft_convenio_entrada.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao",
              "title": "Órgão - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_convenio",
              "title": "Convênio de Entrada - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_concedente",
              "title": "Concedente - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao",
              "title": "Situação do Convênio - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "vr_concedente_atual",
              "title": "Valor Concedente Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "Valor financeiro previsto no convênio para o concedente repassar ao proponente, incluindo termos aditivos.\n",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_proponente_atual",
              "title": "Valor Proponente Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "Valor previsto no convênio para o proponente dar como contrapartida financeira, incluindo termos aditivos.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_orgao"
              ],
              "reference": {
                "fields": [
                  "id_orgao"
                ],
                "resource": "dm_orgao_proponente"
              }
            },
            {
              "fields": [
                "id_situacao"
              ],
              "reference": {
                "fields": [
                  "id_situacao"
                ],
                "resource": "dm_situacao_conv_ent"
              }
            },
            {
              "fields": [
                "id_concedente"
              ],
              "reference": {
                "fields": [
                  "id_concedente"
                ],
                "resource": "dm_concedente"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_convenio"
              ],
              "reference": {
                "fields": [
                  "id_convenio"
                ],
                "resource": "dm_convenio_entrada"
              }
            },
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_convenio_entrada"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "6b5a3441bf22231aa67cdb30d2ef6bad",
          "bytes": 33791,
          "fields": 9,
          "rows": 2156
        }
      },
      "time": 2.855,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 539,
          "rowPosition": 540,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"540\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 541,
          "rowPosition": 542,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"542\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 542,
          "rowPosition": 543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"543\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 543,
          "rowPosition": 544,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"544\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 545,
          "rowPosition": 546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"546\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 546,
          "rowPosition": 547,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"547\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 547,
          "rowPosition": 548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"548\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 548,
          "rowPosition": 549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"549\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 549,
          "rowPosition": 550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"550\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 550,
          "rowPosition": 551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"551\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 551,
          "rowPosition": 552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"552\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 552,
          "rowPosition": 553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"553\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 555,
          "rowPosition": 556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"556\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 556,
          "rowPosition": 557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"557\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 558,
          "rowPosition": 559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"559\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 560,
          "rowPosition": 561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"561\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 563,
          "rowPosition": 564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"564\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 564,
          "rowPosition": 565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"565\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 565,
          "rowPosition": 566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"566\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 566,
          "rowPosition": 567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"567\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 567,
          "rowPosition": 568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"568\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 568,
          "rowPosition": 569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"569\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 569,
          "rowPosition": 570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"570\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 570,
          "rowPosition": 571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"571\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 571,
          "rowPosition": 572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"572\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 572,
          "rowPosition": 573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"573\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 573,
          "rowPosition": 574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"574\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 574,
          "rowPosition": 575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"575\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 575,
          "rowPosition": 576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"576\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 576,
          "rowPosition": 577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"577\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 578,
          "rowPosition": 579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"579\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 579,
          "rowPosition": 580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"580\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 580,
          "rowPosition": 581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"581\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 581,
          "rowPosition": 582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"582\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 582,
          "rowPosition": 583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"583\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 583,
          "rowPosition": 584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"584\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 584,
          "rowPosition": 585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"585\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 586,
          "rowPosition": 587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"587\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 587,
          "rowPosition": 588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"588\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 588,
          "rowPosition": 589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"589\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 589,
          "rowPosition": 590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"590\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 590,
          "rowPosition": 591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"591\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 591,
          "rowPosition": 592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"592\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 593,
          "rowPosition": 594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"594\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 594,
          "rowPosition": 595,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"595\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 596,
          "rowPosition": 597,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"597\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 597,
          "rowPosition": 598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"598\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 598,
          "rowPosition": 599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"599\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 599,
          "rowPosition": 600,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"600\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 600,
          "rowPosition": 601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"601\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 601,
          "rowPosition": 602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"602\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 602,
          "rowPosition": 603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"603\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 603,
          "rowPosition": 604,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"604\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 604,
          "rowPosition": 605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"605\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 606,
          "rowPosition": 607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"607\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 607,
          "rowPosition": 608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"608\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 608,
          "rowPosition": 609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"609\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 609,
          "rowPosition": 610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"610\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 610,
          "rowPosition": 611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"611\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 611,
          "rowPosition": 612,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"612\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 612,
          "rowPosition": 613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"613\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 615,
          "rowPosition": 616,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"616\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 616,
          "rowPosition": 617,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"617\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 617,
          "rowPosition": 618,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"618\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 618,
          "rowPosition": 619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"619\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 620,
          "rowPosition": 621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"621\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 621,
          "rowPosition": 622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"622\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 622,
          "rowPosition": 623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"623\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 623,
          "rowPosition": 624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"624\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 625,
          "rowPosition": 626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"626\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 626,
          "rowPosition": 627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"627\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 628,
          "rowPosition": 629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"629\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 629,
          "rowPosition": 630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"630\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 631,
          "rowPosition": 632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"632\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 632,
          "rowPosition": 633,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"633\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 634,
          "rowPosition": 635,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"635\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 636,
          "rowPosition": 637,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"637\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 637,
          "rowPosition": 638,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"638\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 638,
          "rowPosition": 639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"639\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 643,
          "rowPosition": 644,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"644\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 646,
          "rowPosition": 647,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"647\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 647,
          "rowPosition": 648,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"648\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 648,
          "rowPosition": 649,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"649\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 649,
          "rowPosition": 650,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"650\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 650,
          "rowPosition": 651,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"651\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 652,
          "rowPosition": 653,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"653\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 654,
          "rowPosition": 655,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"655\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 656,
          "rowPosition": 657,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"657\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 657,
          "rowPosition": 658,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"658\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 659,
          "rowPosition": 660,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"660\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 661,
          "rowPosition": 662,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"662\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 662,
          "rowPosition": 663,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"663\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 663,
          "rowPosition": 664,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"664\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 665,
          "rowPosition": 666,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"666\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 666,
          "rowPosition": 667,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"667\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 668,
          "rowPosition": 669,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"669\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 669,
          "rowPosition": 670,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"670\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 670,
          "rowPosition": 671,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"671\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 671,
          "rowPosition": 672,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"672\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 672,
          "rowPosition": 673,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"673\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 673,
          "rowPosition": 674,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"674\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 674,
          "rowPosition": 675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"675\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 675,
          "rowPosition": 676,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"676\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 676,
          "rowPosition": 677,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"677\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 677,
          "rowPosition": 678,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"678\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 678,
          "rowPosition": 679,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"679\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1540,
          "rowPosition": 1541,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1541\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1541,
          "rowPosition": 1542,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1542\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1544,
          "rowPosition": 1545,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1545\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1545,
          "rowPosition": 1546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1546\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1548,
          "rowPosition": 1549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1549\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1550,
          "rowPosition": 1551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1551\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1552,
          "rowPosition": 1553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1553\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1553,
          "rowPosition": 1554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1554\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1554,
          "rowPosition": 1555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1555\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1555,
          "rowPosition": 1556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1556\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1556,
          "rowPosition": 1557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1557\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1557,
          "rowPosition": 1558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1558\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1558,
          "rowPosition": 1559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1559\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1559,
          "rowPosition": 1560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1560\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1560,
          "rowPosition": 1561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1561\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1561,
          "rowPosition": 1562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1562\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1562,
          "rowPosition": 1563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1563\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1563,
          "rowPosition": 1564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1564\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1565,
          "rowPosition": 1566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1566\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1566,
          "rowPosition": 1567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1567\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1569,
          "rowPosition": 1570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1570\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1571,
          "rowPosition": 1572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1572\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1575,
          "rowPosition": 1576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1576\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1581,
          "rowPosition": 1582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1582\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1582,
          "rowPosition": 1583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1583\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1588,
          "rowPosition": 1589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1589\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1607,
          "rowPosition": 1608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1608\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1609,
          "rowPosition": 1610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1610\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1612,
          "rowPosition": 1613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1613\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1618,
          "rowPosition": 1619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1619\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 1619,
          "rowPosition": 1620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1620\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2035,
          "rowPosition": 2036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2036\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2036,
          "rowPosition": 2037,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2037\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2037,
          "rowPosition": 2038,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2038\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2038,
          "rowPosition": 2039,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2039\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2039,
          "rowPosition": 2040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2040\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2040,
          "rowPosition": 2041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2041\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2041,
          "rowPosition": 2042,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2042\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2042,
          "rowPosition": 2043,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2043\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2043,
          "rowPosition": 2044,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2044\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2044,
          "rowPosition": 2045,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2045\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2045,
          "rowPosition": 2046,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2046\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2047,
          "rowPosition": 2048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2048\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2048,
          "rowPosition": 2049,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2049\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2049,
          "rowPosition": 2050,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2050\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2050,
          "rowPosition": 2051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2051\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2051,
          "rowPosition": 2052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2052\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2052,
          "rowPosition": 2053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2053\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2054,
          "rowPosition": 2055,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2055\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2055,
          "rowPosition": 2056,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2056\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2056,
          "rowPosition": 2057,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2057\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2057,
          "rowPosition": 2058,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2058\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2058,
          "rowPosition": 2059,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2059\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2059,
          "rowPosition": 2060,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2060\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2060,
          "rowPosition": 2061,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2061\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2061,
          "rowPosition": 2062,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2062\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2062,
          "rowPosition": 2063,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2063\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2063,
          "rowPosition": 2064,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2064\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2064,
          "rowPosition": 2065,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2065\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2065,
          "rowPosition": 2066,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2066\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2066,
          "rowPosition": 2067,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2067\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2067,
          "rowPosition": 2068,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2068\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2068,
          "rowPosition": 2069,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2069\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2069,
          "rowPosition": 2070,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2070\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2070,
          "rowPosition": 2071,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2071\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2071,
          "rowPosition": 2072,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2072\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2072,
          "rowPosition": 2073,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2073\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2073,
          "rowPosition": 2074,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2074\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2074,
          "rowPosition": 2075,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2075\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2075,
          "rowPosition": 2076,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2076\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2076,
          "rowPosition": 2077,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2077\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2077,
          "rowPosition": 2078,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2078\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2078,
          "rowPosition": 2079,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2079\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2079,
          "rowPosition": 2080,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2080\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2080,
          "rowPosition": 2081,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2081\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2081,
          "rowPosition": 2082,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2082\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2082,
          "rowPosition": 2083,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2083\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2083,
          "rowPosition": 2084,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2084\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2084,
          "rowPosition": 2085,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2085\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2085,
          "rowPosition": 2086,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2086\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2086,
          "rowPosition": 2087,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2087\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2087,
          "rowPosition": 2088,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2088\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2088,
          "rowPosition": 2089,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2089\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2089,
          "rowPosition": 2090,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2090\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2090,
          "rowPosition": 2091,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2091\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2091,
          "rowPosition": 2092,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2092\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2092,
          "rowPosition": 2093,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2093\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2093,
          "rowPosition": 2094,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2094\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2094,
          "rowPosition": 2095,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2095\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2095,
          "rowPosition": 2096,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2096\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2096,
          "rowPosition": 2097,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2097\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2097,
          "rowPosition": 2098,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2098\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2098,
          "rowPosition": 2099,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2099\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2099,
          "rowPosition": 2100,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2100\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2100,
          "rowPosition": 2101,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2101\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2101,
          "rowPosition": 2102,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2102\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_orgao",
            "id_convenio",
            "id_concedente",
            "id_unidade_orc",
            "id_situacao",
            "ano_particao",
            "vr_concedente_atual",
            "vr_proponente_atual"
          ],
          "rowNumber": 2102,
          "rowPosition": 2103,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"2103\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 203
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 203,
    "tasks": 1
  },
  "valid": false
}