{
  "version": "4.38.0",
  "time": 412.131,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "ced8930cffd72462e70356cdccc49bc2",
          "bytes": 58001238,
          "fields": 27,
          "rows": 1902676
        }
      },
      "time": 412.131,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43583",
            "14",
            "1831101",
            "97",
            "1",
            "1",
            "66",
            "61601",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "381927",
            "78151",
            "1174",
            "1831312",
            "2538",
            "2259",
            "2022",
            "2022-11-16",
            "633.0000",
            "21.0000",
            "13293.00",
            "20.8500",
            "13198.05",
            "13198.05"
          ],
          "rowNumber": 1812751,
          "rowPosition": 1812752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78151\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812752\" violates the foreign key: for \"id_contrato\": values \"78151\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43494",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "31623",
            "1",
            "77",
            "533",
            "9643",
            "90741",
            "378620",
            "78114",
            "889",
            "1831749",
            "2594",
            "2838",
            "2022",
            "2022-09-26",
            "0.0000",
            "80231.0000",
            "80231.00",
            "78564.9000",
            "78564.90",
            "78564.90"
          ],
          "rowNumber": 1813390,
          "rowPosition": 1813391,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78114\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813391\" violates the foreign key: for \"id_contrato\": values \"78114\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "1",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "72791",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "382663",
            "46296",
            "889",
            "1831808",
            "2806",
            "1760",
            "2022",
            "2022-11-24",
            "0.0000",
            "5600.0000",
            "5600.00",
            "5600.0000",
            "5600.00",
            "5600.00"
          ],
          "rowNumber": 1817788,
          "rowPosition": 1817789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72791\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1817789\" violates the foreign key: for \"id_contratado\": values \"72791\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43512",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31560",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "381278",
            "78149",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-04",
            "0.0000",
            "5895.4000",
            "5895.40",
            "2000.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1818077,
          "rowPosition": 1818078,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78149\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818078\" violates the foreign key: for \"id_contrato\": values \"78149\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "14",
            "1831099",
            "90",
            "1",
            "1",
            "606",
            "72270",
            "1",
            "77",
            "533",
            "6890",
            "154575",
            "381262",
            "78119",
            "889",
            "1831584",
            "2804",
            "2001",
            "2022",
            "2022-11-04",
            "0.0000",
            "2175.0000",
            "2175.00",
            "2160.0000",
            "2160.00",
            "2160.00"
          ],
          "rowNumber": 1818079,
          "rowPosition": 1818080,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78119\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818080\" violates the foreign key: for \"id_contrato\": values \"78119\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43576",
            "14",
            "1831105",
            "91",
            "1",
            "1",
            "38",
            "35630",
            "1",
            "77",
            "700",
            "20204",
            "92477",
            "380093",
            "78115",
            "889",
            "1831443",
            "2954",
            "3042",
            "2022",
            "2022-10-17",
            "0.0000",
            "10400.0000",
            "10400.00",
            "10400.0000",
            "10400.00",
            "10400.00"
          ],
          "rowNumber": 1821447,
          "rowPosition": 1821448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78115\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821448\" violates the foreign key: for \"id_contrato\": values \"78115\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44416",
            "15",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "381380",
            "78138",
            "190",
            "1831313",
            "2928",
            "2885",
            "2022",
            "2022-11-07",
            "2000.0000",
            "5.6300",
            "11257.20",
            "5.6300",
            "11257.20",
            "11257.20"
          ],
          "rowNumber": 1829794,
          "rowPosition": 1829795,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78138\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829795\" violates the foreign key: for \"id_contrato\": values \"78138\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44416",
            "15",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "381380",
            "78138",
            "190",
            "1831313",
            "2928",
            "2885",
            "2022",
            "2022-11-07",
            "19000.0000",
            "3.9300",
            "74595.90",
            "3.9300",
            "74595.90",
            "74595.90"
          ],
          "rowNumber": 1829795,
          "rowPosition": 1829796,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78138\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829796\" violates the foreign key: for \"id_contrato\": values \"78138\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "54597",
            "1",
            "32",
            "100",
            "18579",
            "251627",
            "381396",
            "78142",
            "889",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-11-07",
            "5.0000",
            "803.8800",
            "4019.40",
            "803.8800",
            "4019.40",
            "4019.40"
          ],
          "rowNumber": 1829813,
          "rowPosition": 1829814,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829814\" violates the foreign key: for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "54597",
            "1",
            "32",
            "100",
            "18579",
            "5474",
            "381396",
            "78142",
            "933",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-11-07",
            "1.0000",
            "1083.9500",
            "1083.95",
            "846.7600",
            "846.76",
            "846.76"
          ],
          "rowNumber": 1829814,
          "rowPosition": 1829815,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829815\" violates the foreign key: for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "54597",
            "1",
            "32",
            "100",
            "18579",
            "5474",
            "381396",
            "78142",
            "933",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-11-07",
            "40.0000",
            "1083.9500",
            "43358.00",
            "846.7600",
            "33870.40",
            "33870.40"
          ],
          "rowNumber": 1830674,
          "rowPosition": 1830675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830675\" violates the foreign key: for \"id_contrato\": values \"78142\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "58",
            "732",
            "381",
            "5524",
            "381396",
            "78134",
            "941",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-07",
            "2.0000",
            "11567.0500",
            "23134.10",
            "11567.0500",
            "23134.10",
            "23134.10"
          ],
          "rowNumber": 1830675,
          "rowPosition": 1830676,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78134\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830676\" violates the foreign key: for \"id_contrato\": values \"78134\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43994",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "58",
            "732",
            "8004",
            "11056",
            "381362",
            "78134",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-07",
            "200.0000",
            "53.3300",
            "10666.00",
            "52.3600",
            "10472.00",
            "10472.00"
          ],
          "rowNumber": 1832512,
          "rowPosition": 1832513,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78134\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832513\" violates the foreign key: for \"id_contrato\": values \"78134\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "1",
            "1831103",
            "94",
            "1",
            "1",
            "66",
            "1538",
            "1",
            "39",
            "834",
            "22130",
            "383231",
            "382276",
            "78120",
            "1729",
            "1831739",
            "3067",
            "2212",
            "2022",
            "2022-11-21",
            "0.0000",
            "4049.0000",
            "4049.00",
            "4049.0000",
            "4049.00",
            "4049.00"
          ],
          "rowNumber": 1851370,
          "rowPosition": 1851371,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78120\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851371\" violates the foreign key: for \"id_contrato\": values \"78120\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "30672",
            "1",
            "77",
            "533",
            "17583",
            "91821",
            "382331",
            "78145",
            "889",
            "1831554",
            "2738",
            "2045",
            "2022",
            "2022-11-21",
            "0.0000",
            "132900.0000",
            "132900.00",
            "60600.0000",
            "60600.00",
            "60600.00"
          ],
          "rowNumber": 1851371,
          "rowPosition": 1851372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78145\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851372\" violates the foreign key: for \"id_contrato\": values \"78145\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43550",
            "4",
            "1831099",
            "90",
            "1",
            "1",
            "66",
            "22658",
            "1",
            "51",
            "80",
            "20153",
            "120120",
            "382318",
            "78131",
            "889",
            "1831507",
            "3067",
            "2001",
            "2022",
            "2022-11-21",
            "0.0000",
            "1179984.0000",
            "1179984.00",
            "939999.9400",
            "939999.94",
            "939999.94"
          ],
          "rowNumber": 1851380,
          "rowPosition": 1851381,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78131\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851381\" violates the foreign key: for \"id_contrato\": values \"78131\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43568",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "34277",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "382306",
            "78136",
            "889",
            "1831744",
            "2597",
            "2046",
            "2022",
            "2022-11-21",
            "0.0000",
            "381689.4000",
            "381689.40",
            "178999.9900",
            "178999.99",
            "178999.99"
          ],
          "rowNumber": 1851385,
          "rowPosition": 1851386,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78136\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851386\" violates the foreign key: for \"id_contrato\": values \"78136\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43568",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "21502",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "382306",
            "78137",
            "889",
            "1831744",
            "2597",
            "2046",
            "2022",
            "2022-11-21",
            "0.0000",
            "79500.0000",
            "79500.00",
            "53000.0000",
            "53000.00",
            "53000.00"
          ],
          "rowNumber": 1851386,
          "rowPosition": 1851387,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78137\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851387\" violates the foreign key: for \"id_contrato\": values \"78137\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44430",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "38482",
            "1",
            "3",
            "627",
            "16366",
            "269346",
            "382343",
            "78129",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-21",
            "2.0000",
            "1550.0000",
            "3100.00",
            "1550.0000",
            "3100.00",
            "3100.00"
          ],
          "rowNumber": 1853070,
          "rowPosition": 1853071,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78129\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853071\" violates the foreign key: for \"id_contrato\": values \"78129\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43513",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "21170",
            "1",
            "26",
            "170",
            "8339",
            "10882",
            "382051",
            "78122",
            "1579",
            "1831313",
            "2923",
            "2081",
            "2022",
            "2022-11-17",
            "240.0000",
            "40.0000",
            "9600.00",
            "40.0000",
            "9600.00",
            "9600.00"
          ],
          "rowNumber": 1857310,
          "rowPosition": 1857311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78122\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857311\" violates the foreign key: for \"id_contrato\": values \"78122\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226216",
            "382077",
            "78132",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-17",
            "4.0000",
            "4217.5700",
            "16870.28",
            "4217.5700",
            "16870.28",
            "16870.28"
          ],
          "rowNumber": 1857979,
          "rowPosition": 1857980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78132\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857980\" violates the foreign key: for \"id_contrato\": values \"78132\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382098",
            "78126",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-17",
            "1.0000",
            "4921.1000",
            "4921.10",
            "4921.1000",
            "4921.10",
            "4921.10"
          ],
          "rowNumber": 1857980,
          "rowPosition": 1857981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78126\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857981\" violates the foreign key: for \"id_contrato\": values \"78126\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "381994",
            "78139",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-17",
            "2.0000",
            "4921.1000",
            "9842.20",
            "4921.1000",
            "9842.20",
            "9842.20"
          ],
          "rowNumber": 1857981,
          "rowPosition": 1857982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78139\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857982\" violates the foreign key: for \"id_contrato\": values \"78139\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382007",
            "78146",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-17",
            "2.0000",
            "4921.1000",
            "9842.20",
            "4921.1000",
            "9842.20",
            "9842.20"
          ],
          "rowNumber": 1857982,
          "rowPosition": 1857983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78146\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857983\" violates the foreign key: for \"id_contrato\": values \"78146\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382124",
            "78133",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-17",
            "15.0000",
            "4921.1000",
            "73816.50",
            "4921.1000",
            "73816.50",
            "73816.50"
          ],
          "rowNumber": 1857983,
          "rowPosition": 1857984,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78133\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857984\" violates the foreign key: for \"id_contrato\": values \"78133\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43512",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32957",
            "1",
            "77",
            "273",
            "14784",
            "91505",
            "382346",
            "78128",
            "889",
            "1831537",
            "2954",
            "2925",
            "2022",
            "2022-11-21",
            "0.0000",
            "10680.0000",
            "10680.00",
            "8499.9600",
            "8499.96",
            "8499.96"
          ],
          "rowNumber": 1858027,
          "rowPosition": 1858028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78128\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858028\" violates the foreign key: for \"id_contrato\": values \"78128\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43578",
            "1",
            "1831101",
            "97",
            "1",
            "1",
            "66",
            "72750",
            "1",
            "77",
            "479",
            "7690",
            "158768",
            "382292",
            "78135",
            "889",
            "1831808",
            "2602",
            "2259",
            "2022",
            "2022-11-21",
            "0.0000",
            "133090.0600",
            "133090.06",
            "131055.0500",
            "131055.05",
            "131055.05"
          ],
          "rowNumber": 1858039,
          "rowPosition": 1858040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78135\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858040\" violates the foreign key: for \"id_contrato\": values \"78135\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "17",
            "1831079",
            "76",
            "1",
            "1",
            "883",
            "67434",
            "1",
            "3",
            "627",
            "91",
            "201948",
            "379523",
            "78130",
            "889",
            "1831295",
            "2611",
            "2046",
            "2022",
            "2022-10-07",
            "6.0000",
            "3200.0000",
            "19200.00",
            "3200.0000",
            "19200.00",
            "19200.00"
          ],
          "rowNumber": 1878468,
          "rowPosition": 1878469,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78130\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1878469\" violates the foreign key: for \"id_contrato\": values \"78130\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50309",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "814",
            "597",
            "1",
            "51",
            "584",
            "9713",
            "92336",
            "382238",
            "78121",
            "981",
            "1831508",
            "2670",
            "2925",
            "2021",
            "2022-11-18",
            "0.0000",
            "13790.0000",
            "13790.00",
            "13790.0000",
            "13790.00",
            "13790.00"
          ],
          "rowNumber": 1888911,
          "rowPosition": 1888912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888912\" violates the foreign key: for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50309",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "814",
            "597",
            "1",
            "51",
            "584",
            "9713",
            "92336",
            "382238",
            "78121",
            "981",
            "1831508",
            "2670",
            "2925",
            "2021",
            "2022-11-18",
            "0.0000",
            "16110.0000",
            "16110.00",
            "16110.0000",
            "16110.00",
            "16110.00"
          ],
          "rowNumber": 1888922,
          "rowPosition": 1888923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888923\" violates the foreign key: for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50309",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "814",
            "597",
            "1",
            "51",
            "584",
            "9713",
            "92336",
            "382238",
            "78121",
            "981",
            "1831508",
            "2670",
            "2925",
            "2021",
            "2022-11-18",
            "0.0000",
            "16250.0000",
            "16250.00",
            "16250.0000",
            "16250.00",
            "16250.00"
          ],
          "rowNumber": 1888923,
          "rowPosition": 1888924,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888924\" violates the foreign key: for \"id_contrato\": values \"78121\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "624",
            "83",
            "160798",
            "381740",
            "78116",
            "889",
            "1831882",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "8000.0000",
            "23.9900",
            "191920.00",
            "23.9900",
            "191920.00",
            "191920.00"
          ],
          "rowNumber": 1891051,
          "rowPosition": 1891052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891052\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "80",
            "621",
            "364",
            "132899",
            "381740",
            "78116",
            "229",
            "1831306",
            "2796",
            "3043",
            "2022",
            "2022-11-11",
            "25.0000",
            "120.1000",
            "3002.50",
            "112.0000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1891052,
          "rowPosition": 1891053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891053\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "80",
            "308",
            "10895",
            "53569",
            "381740",
            "78116",
            "889",
            "1831306",
            "2994",
            "3043",
            "2022",
            "2022-11-11",
            "150.0000",
            "89.9000",
            "13485.00",
            "35.0000",
            "5250.00",
            "5250.00"
          ],
          "rowNumber": 1891053,
          "rowPosition": 1891054,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891054\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "107",
            "17819",
            "104981",
            "381740",
            "78116",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-11",
            "50.0000",
            "78.4900",
            "3924.50",
            "78.4900",
            "3924.50",
            "3924.50"
          ],
          "rowNumber": 1891054,
          "rowPosition": 1891055,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891055\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "8394",
            "229875",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "240.0000",
            "15.9000",
            "3816.00",
            "10.8700",
            "2608.80",
            "2608.80"
          ],
          "rowNumber": 1891055,
          "rowPosition": 1891056,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891056\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "18958",
            "162806",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "50.0000",
            "149.6600",
            "7483.00",
            "149.6600",
            "7483.00",
            "7483.00"
          ],
          "rowNumber": 1891056,
          "rowPosition": 1891057,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891057\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "340",
            "10528",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "100.0000",
            "13.2000",
            "1320.00",
            "9.2400",
            "924.00",
            "924.00"
          ],
          "rowNumber": 1891057,
          "rowPosition": 1891058,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891058\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "340",
            "4892",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "100.0000",
            "13.2000",
            "1320.00",
            "9.2400",
            "924.00",
            "924.00"
          ],
          "rowNumber": 1891058,
          "rowPosition": 1891059,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891059\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "503",
            "356510",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "10000.0000",
            "3.5900",
            "35900.00",
            "2.3500",
            "23500.00",
            "23500.00"
          ],
          "rowNumber": 1891059,
          "rowPosition": 1891060,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891060\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "990",
            "359442",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "40.0000",
            "382.1900",
            "15287.60",
            "382.1900",
            "15287.60",
            "15287.60"
          ],
          "rowNumber": 1891060,
          "rowPosition": 1891061,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891061\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19141",
            "1",
            "42",
            "399",
            "3870",
            "357983",
            "381740",
            "78116",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "2000.0000",
            "11.9900",
            "23980.00",
            "11.9900",
            "23980.00",
            "23980.00"
          ],
          "rowNumber": 1891061,
          "rowPosition": 1891062,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891062\" violates the foreign key: for \"id_contrato\": values \"78116\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44418",
            "14",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "57690",
            "1",
            "77",
            "808",
            "4383",
            "117116",
            "382605",
            "78124",
            "889",
            "1899033",
            "2869",
            "2045",
            "2022",
            "2022-11-23",
            "0.0000",
            "17200.0000",
            "17200.00",
            "11000.0000",
            "11000.00",
            "11000.00"
          ],
          "rowNumber": 1892182,
          "rowPosition": 1892183,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78124\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892183\" violates the foreign key: for \"id_contrato\": values \"78124\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44431",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382531",
            "78127",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-23",
            "10.0000",
            "4921.1000",
            "49211.00",
            "4921.1000",
            "49211.00",
            "49211.00"
          ],
          "rowNumber": 1892186,
          "rowPosition": 1892187,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78127\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892187\" violates the foreign key: for \"id_contrato\": values \"78127\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44431",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "38482",
            "1",
            "3",
            "627",
            "16366",
            "269346",
            "382629",
            "78113",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-23",
            "1.0000",
            "1550.0000",
            "1550.00",
            "1550.0000",
            "1550.00",
            "1550.00"
          ],
          "rowNumber": 1892187,
          "rowPosition": 1892188,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78113\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892188\" violates the foreign key: for \"id_contrato\": values \"78113\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "68447",
            "1",
            "3",
            "627",
            "16158",
            "147571",
            "381797",
            "78123",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-11",
            "1.0000",
            "1227.0000",
            "1227.00",
            "1227.0000",
            "1227.00",
            "1227.00"
          ],
          "rowNumber": 1894697,
          "rowPosition": 1894698,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78123\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894698\" violates the foreign key: for \"id_contrato\": values \"78123\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "59714",
            "1",
            "10",
            "501",
            "5144",
            "13161",
            "381740",
            "78118",
            "148",
            "1831307",
            "2586",
            "3043",
            "2022",
            "2022-11-11",
            "200.0000",
            "320.0000",
            "64000.00",
            "119.0000",
            "23800.00",
            "23800.00"
          ],
          "rowNumber": 1895594,
          "rowPosition": 1895595,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78118\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895595\" violates the foreign key: for \"id_contrato\": values \"78118\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "100",
            "10996",
            "95274",
            "381740",
            "78143",
            "189",
            "1831400",
            "2796",
            "3043",
            "2022",
            "2022-11-11",
            "390.0000",
            "29.2300",
            "11397.75",
            "29.2300",
            "11397.75",
            "11397.75"
          ],
          "rowNumber": 1895595,
          "rowPosition": 1895596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78143\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895596\" violates the foreign key: for \"id_contrato\": values \"78143\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19898",
            "1",
            "42",
            "399",
            "10980",
            "136885",
            "381740",
            "78141",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "17000.0000",
            "2.5500",
            "43350.00",
            "1.1400",
            "19380.00",
            "19380.00"
          ],
          "rowNumber": 1895596,
          "rowPosition": 1895597,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78141\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895597\" violates the foreign key: for \"id_contrato\": values \"78141\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "25971",
            "1",
            "42",
            "399",
            "5637",
            "34058",
            "381740",
            "78117",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "60.0000",
            "105.5500",
            "6333.00",
            "105.5500",
            "6333.00",
            "6333.00"
          ],
          "rowNumber": 1895597,
          "rowPosition": 1895598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78117\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895598\" violates the foreign key: for \"id_contrato\": values \"78117\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "25971",
            "1",
            "42",
            "399",
            "5637",
            "52137",
            "381740",
            "78117",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "90.0000",
            "111.1500",
            "10003.50",
            "111.1500",
            "10003.50",
            "10003.50"
          ],
          "rowNumber": 1895598,
          "rowPosition": 1895599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78117\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895599\" violates the foreign key: for \"id_contrato\": values \"78117\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20176",
            "1",
            "42",
            "107",
            "5646",
            "367552",
            "381740",
            "78148",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "6000.0000",
            "4.5000",
            "27000.00",
            "0.7700",
            "4620.00",
            "4620.00"
          ],
          "rowNumber": 1895599,
          "rowPosition": 1895600,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78148\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895600\" violates the foreign key: for \"id_contrato\": values \"78148\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20176",
            "1",
            "42",
            "107",
            "5646",
            "367547",
            "381740",
            "78148",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "16000.0000",
            "3.0000",
            "48000.00",
            "0.7000",
            "11200.00",
            "11200.00"
          ],
          "rowNumber": 1895600,
          "rowPosition": 1895601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78148\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895601\" violates the foreign key: for \"id_contrato\": values \"78148\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19426",
            "1",
            "80",
            "308",
            "10895",
            "131264",
            "381740",
            "78125",
            "889",
            "1831306",
            "2994",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "101.5000",
            "2030.00",
            "101.5000",
            "2030.00",
            "2030.00"
          ],
          "rowNumber": 1895601,
          "rowPosition": 1895602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78125\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895602\" violates the foreign key: for \"id_contrato\": values \"78125\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "8343",
            "1",
            "18",
            "22",
            "11158",
            "39681",
            "381740",
            "78150",
            "889",
            "1831311",
            "2994",
            "3043",
            "2022",
            "2022-11-11",
            "300.0000",
            "51.0000",
            "15300.00",
            "32.0000",
            "9600.00",
            "9600.00"
          ],
          "rowNumber": 1895602,
          "rowPosition": 1895603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78150\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895603\" violates the foreign key: for \"id_contrato\": values \"78150\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19426",
            "1",
            "80",
            "308",
            "10895",
            "268266",
            "381740",
            "78125",
            "889",
            "1831306",
            "2994",
            "3043",
            "2022",
            "2022-11-11",
            "40.0000",
            "138.4300",
            "5537.00",
            "35.6500",
            "1426.00",
            "1426.00"
          ],
          "rowNumber": 1895604,
          "rowPosition": 1895605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78125\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895605\" violates the foreign key: for \"id_contrato\": values \"78125\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "29623",
            "1",
            "42",
            "107",
            "11040",
            "130388",
            "381740",
            "78147",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "200.0000",
            "4000.00",
            "200.0000",
            "4000.00",
            "4000.00"
          ],
          "rowNumber": 1895605,
          "rowPosition": 1895606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895606\" violates the foreign key: for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "29623",
            "1",
            "42",
            "107",
            "11040",
            "125210",
            "381740",
            "78147",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "200.0000",
            "4000.00",
            "200.0000",
            "4000.00",
            "4000.00"
          ],
          "rowNumber": 1895606,
          "rowPosition": 1895607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895607\" violates the foreign key: for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "29623",
            "1",
            "42",
            "107",
            "11040",
            "125209",
            "381740",
            "78147",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "200.0000",
            "4000.00",
            "200.0000",
            "4000.00",
            "4000.00"
          ],
          "rowNumber": 1895607,
          "rowPosition": 1895608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895608\" violates the foreign key: for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "29623",
            "1",
            "42",
            "107",
            "11040",
            "87767",
            "381740",
            "78147",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "179.3500",
            "3587.00",
            "179.3500",
            "3587.00",
            "3587.00"
          ],
          "rowNumber": 1895608,
          "rowPosition": 1895609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895609\" violates the foreign key: for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "29623",
            "1",
            "42",
            "107",
            "11040",
            "87766",
            "381740",
            "78147",
            "889",
            "1831334",
            "2923",
            "3043",
            "2022",
            "2022-11-11",
            "20.0000",
            "200.0000",
            "4000.00",
            "200.0000",
            "4000.00",
            "4000.00"
          ],
          "rowNumber": 1895609,
          "rowPosition": 1895610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895610\" violates the foreign key: for \"id_contrato\": values \"78147\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382226",
            "78144",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-18",
            "10.0000",
            "4921.1000",
            "49211.00",
            "4921.1000",
            "49211.00",
            "49211.00"
          ],
          "rowNumber": 1899742,
          "rowPosition": 1899743,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78144\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899743\" violates the foreign key: for \"id_contrato\": values \"78144\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "148162",
            "382422",
            "78140",
            "889",
            "1831952",
            "2927",
            "2210",
            "2022",
            "2022-11-22",
            "14628.0000",
            "32.2600",
            "471899.28",
            "32.2600",
            "471899.28",
            "471899.28"
          ],
          "rowNumber": 1900224,
          "rowPosition": 1900225,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78140\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900225\" violates the foreign key: for \"id_contrato\": values \"78140\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "139833",
            "382422",
            "78140",
            "889",
            "1831952",
            "2927",
            "2210",
            "2022",
            "2022-11-22",
            "14627.0000",
            "32.2600",
            "471867.02",
            "32.2600",
            "471867.02",
            "471867.02"
          ],
          "rowNumber": 1900225,
          "rowPosition": 1900226,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78140\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900226\" violates the foreign key: for \"id_contrato\": values \"78140\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 64
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 64,
    "tasks": 1
  },
  "valid": false
}