{
  "version": "4.38.0",
  "time": 408.558,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "fce02de2aa4b9dd5584d75e562f31e12",
          "bytes": 57979850,
          "fields": 27,
          "rows": 1901894
        }
      },
      "time": 408.558,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43555",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "66",
            "55805",
            "1",
            "41",
            "806",
            "17688",
            "93770",
            "380817",
            "78100",
            "889",
            "1831536",
            "2594",
            "2082",
            "2022",
            "2022-10-26",
            "0.0000",
            "15150.0000",
            "15150.00",
            "15150.0000",
            "15150.00",
            "15150.00"
          ],
          "rowNumber": 1814631,
          "rowPosition": 1814632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78100\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814632\" violates the foreign key: for \"id_contrato\": values \"78100\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43478",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31560",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "381267",
            "78109",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-04",
            "0.0000",
            "32000.0000",
            "32000.00",
            "32000.0000",
            "32000.00",
            "32000.00"
          ],
          "rowNumber": 1817606,
          "rowPosition": 1817607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78109\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817607\" violates the foreign key: for \"id_contrato\": values \"78109\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "637",
            "33135",
            "1",
            "66",
            "702",
            "4422",
            "93091",
            "381470",
            "78097",
            "889",
            "1831575",
            "2837",
            "3293",
            "2022",
            "2022-11-08",
            "0.0000",
            "1574592.0000",
            "1574592.00",
            "752468.1600",
            "752468.16",
            "752468.16"
          ],
          "rowNumber": 1821664,
          "rowPosition": 1821665,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78097\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821665\" violates the foreign key: for \"id_contrato\": values \"78097\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "24550",
            "1",
            "55",
            "731",
            "8273",
            "163135",
            "382259",
            "78086",
            "889",
            "1831986",
            "2744",
            "2081",
            "2022",
            "2022-11-21",
            "2.0000",
            "3333.2000",
            "6666.40",
            "1170.0000",
            "2340.00",
            "2340.00"
          ],
          "rowNumber": 1850900,
          "rowPosition": 1850901,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78086\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850901\" violates the foreign key: for \"id_contrato\": values \"78086\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "600",
            "3378",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "382264",
            "78112",
            "889",
            "1831360",
            "2670",
            "3043",
            "2022",
            "2022-11-21",
            "0.0000",
            "4090.0000",
            "4090.00",
            "3800.0000",
            "3800.00",
            "3800.00"
          ],
          "rowNumber": 1850909,
          "rowPosition": 1850910,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78112\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850910\" violates the foreign key: for \"id_contrato\": values \"78112\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "856",
            "13320",
            "1",
            "77",
            "533",
            "19020",
            "146071",
            "382106",
            "78094",
            "889",
            "1831368",
            "2774",
            "2270",
            "2022",
            "2022-11-17",
            "0.0000",
            "2167000.0000",
            "2167000.00",
            "2000000.0000",
            "2000000.00",
            "2000000.00"
          ],
          "rowNumber": 1856837,
          "rowPosition": 1856838,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78094\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1856838\" violates the foreign key: for \"id_contrato\": values \"78094\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "15",
            "1831067",
            "64",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382042",
            "78092",
            "889",
            "1831295",
            "2611",
            "1775",
            "2022",
            "2022-11-17",
            "30.0000",
            "4921.1000",
            "147633.00",
            "4921.1000",
            "147633.00",
            "147633.00"
          ],
          "rowNumber": 1857506,
          "rowPosition": 1857507,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78092\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857507\" violates the foreign key: for \"id_contrato\": values \"78092\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "33457",
            "379749",
            "78110",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-10-13",
            "40000.0000",
            "0.3900",
            "15512.00",
            "0.1800",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1878549,
          "rowPosition": 1878550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1878550\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "33455",
            "379749",
            "78098",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-10-13",
            "3000.0000",
            "0.4900",
            "1470.00",
            "0.1300",
            "390.00",
            "390.00"
          ],
          "rowNumber": 1879399,
          "rowPosition": 1879400,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879400\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "31840",
            "379749",
            "78098",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-10-13",
            "12000.0000",
            "0.2900",
            "3480.00",
            "0.1500",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1879400,
          "rowPosition": 1879401,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879401\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "18685",
            "38725",
            "379758",
            "78089",
            "893",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "8.0000",
            "74.7400",
            "597.92",
            "58.0000",
            "464.00",
            "464.00"
          ],
          "rowNumber": 1879401,
          "rowPosition": 1879402,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879402\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "18685",
            "19995",
            "379758",
            "78098",
            "893",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "10.0000",
            "132.1400",
            "1321.40",
            "86.5000",
            "865.00",
            "865.00"
          ],
          "rowNumber": 1879403,
          "rowPosition": 1879404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879404\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "13878",
            "128213",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "12500.0000",
            "0.6500",
            "8125.00",
            "0.0800",
            "1000.00",
            "1000.00"
          ],
          "rowNumber": 1879404,
          "rowPosition": 1879405,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879405\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "39631",
            "1",
            "58",
            "732",
            "772",
            "32260",
            "379758",
            "78103",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "9000.0000",
            "1.9000",
            "17100.00",
            "0.4800",
            "4320.00",
            "4320.00"
          ],
          "rowNumber": 1879405,
          "rowPosition": 1879406,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879406\" violates the foreign key: for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "17950",
            "1",
            "58",
            "732",
            "13878",
            "125946",
            "379758",
            "78104",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "10000.0000",
            "1.9500",
            "19450.00",
            "0.9800",
            "9800.00",
            "9800.00"
          ],
          "rowNumber": 1879406,
          "rowPosition": 1879407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879407\" violates the foreign key: for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "17950",
            "1",
            "58",
            "732",
            "772",
            "77339",
            "379758",
            "78104",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "212000.0000",
            "1.6500",
            "349800.00",
            "0.5800",
            "122960.00",
            "122960.00"
          ],
          "rowNumber": 1879407,
          "rowPosition": 1879408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879408\" violates the foreign key: for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "17950",
            "1",
            "58",
            "732",
            "772",
            "100424",
            "379758",
            "78104",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "5000.0000",
            "1.6500",
            "8250.00",
            "0.9000",
            "4500.00",
            "4500.00"
          ],
          "rowNumber": 1879408,
          "rowPosition": 1879409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879409\" violates the foreign key: for \"id_contrato\": values \"78104\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "772",
            "32955",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1250.0000",
            "5.1100",
            "6387.50",
            "1.4900",
            "1862.50",
            "1862.50"
          ],
          "rowNumber": 1879409,
          "rowPosition": 1879410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879410\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "33455",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "3000.0000",
            "0.4900",
            "1470.00",
            "0.1300",
            "390.00",
            "390.00"
          ],
          "rowNumber": 1879410,
          "rowPosition": 1879411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879411\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "18685",
            "19995",
            "379758",
            "78098",
            "893",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "22.0000",
            "132.1400",
            "2907.08",
            "86.5000",
            "1903.00",
            "1903.00"
          ],
          "rowNumber": 1879411,
          "rowPosition": 1879412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879412\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "31840",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "18000.0000",
            "0.2900",
            "5220.00",
            "0.1500",
            "2700.00",
            "2700.00"
          ],
          "rowNumber": 1879412,
          "rowPosition": 1879413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879413\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "39631",
            "1",
            "58",
            "732",
            "13878",
            "94986",
            "379758",
            "78103",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "4400.0000",
            "2.4700",
            "10868.00",
            "0.7000",
            "3080.00",
            "3080.00"
          ],
          "rowNumber": 1879413,
          "rowPosition": 1879414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879414\" violates the foreign key: for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "31837",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "87300.0000",
            "0.4000",
            "34920.00",
            "0.1600",
            "13968.00",
            "13968.00"
          ],
          "rowNumber": 1879414,
          "rowPosition": 1879415,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879415\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "13878",
            "32149",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "3400.0000",
            "2.1800",
            "7412.00",
            "0.8800",
            "2992.00",
            "2992.00"
          ],
          "rowNumber": 1879415,
          "rowPosition": 1879416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879416\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "31835",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "85500.0000",
            "0.7000",
            "59850.00",
            "0.1300",
            "11115.00",
            "11115.00"
          ],
          "rowNumber": 1879416,
          "rowPosition": 1879417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879417\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "182790",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "26000.0000",
            "0.6500",
            "16900.00",
            "0.1500",
            "3900.00",
            "3900.00"
          ],
          "rowNumber": 1879417,
          "rowPosition": 1879418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879418\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "77340",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "2000.0000",
            "1.3800",
            "2760.00",
            "0.3900",
            "780.00",
            "780.00"
          ],
          "rowNumber": 1879418,
          "rowPosition": 1879419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879419\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "7965",
            "117654",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "12900.0000",
            "1.9300",
            "24897.00",
            "1.1500",
            "14835.00",
            "14835.00"
          ],
          "rowNumber": 1879419,
          "rowPosition": 1879420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879420\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "33457",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "7600.0000",
            "0.3900",
            "2947.28",
            "0.1800",
            "1368.00",
            "1368.00"
          ],
          "rowNumber": 1879420,
          "rowPosition": 1879421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879421\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "13878",
            "192260",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "36000.0000",
            "0.3800",
            "13680.00",
            "0.2500",
            "9000.00",
            "9000.00"
          ],
          "rowNumber": 1879422,
          "rowPosition": 1879423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879423\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "32160",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "4700.0000",
            "0.5200",
            "2444.00",
            "0.5200",
            "2444.00",
            "2444.00"
          ],
          "rowNumber": 1879423,
          "rowPosition": 1879424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879424\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "18685",
            "119867",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1000.0000",
            "1.1800",
            "1180.00",
            "1.1800",
            "1180.00",
            "1180.00"
          ],
          "rowNumber": 1879424,
          "rowPosition": 1879425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879425\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "13878",
            "128213",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "4000.0000",
            "0.6500",
            "2600.00",
            "0.0800",
            "320.00",
            "320.00"
          ],
          "rowNumber": 1879425,
          "rowPosition": 1879426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879426\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "31837",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1000.0000",
            "0.4000",
            "400.00",
            "0.1600",
            "160.00",
            "160.00"
          ],
          "rowNumber": 1879426,
          "rowPosition": 1879427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879427\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "19898",
            "1",
            "58",
            "732",
            "13878",
            "192260",
            "379758",
            "78089",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "5000.0000",
            "0.3800",
            "1900.00",
            "0.2500",
            "1250.00",
            "1250.00"
          ],
          "rowNumber": 1879427,
          "rowPosition": 1879428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879428\" violates the foreign key: for \"id_contrato\": values \"78089\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "32159",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "500.0000",
            "1.8900",
            "945.00",
            "0.4300",
            "215.00",
            "215.00"
          ],
          "rowNumber": 1879428,
          "rowPosition": 1879429,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879429\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "33058",
            "1",
            "58",
            "732",
            "13878",
            "31840",
            "379758",
            "78098",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "2000.0000",
            "0.2900",
            "580.00",
            "0.1500",
            "300.00",
            "300.00"
          ],
          "rowNumber": 1879429,
          "rowPosition": 1879430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879430\" violates the foreign key: for \"id_contrato\": values \"78098\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "36522",
            "1",
            "58",
            "732",
            "13878",
            "31835",
            "379758",
            "78110",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "5000.0000",
            "0.7000",
            "3500.00",
            "0.1300",
            "650.00",
            "650.00"
          ],
          "rowNumber": 1879430,
          "rowPosition": 1879431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879431\" violates the foreign key: for \"id_contrato\": values \"78110\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "39631",
            "1",
            "58",
            "732",
            "13878",
            "94986",
            "379758",
            "78103",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "2000.0000",
            "2.4700",
            "4940.00",
            "0.7000",
            "1400.00",
            "1400.00"
          ],
          "rowNumber": 1879431,
          "rowPosition": 1879432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879432\" violates the foreign key: for \"id_contrato\": values \"78103\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3798",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "3.0000",
            "1654.0000",
            "4962.00",
            "541.5300",
            "1624.59",
            "1624.59"
          ],
          "rowNumber": 1879432,
          "rowPosition": 1879433,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879433\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3794",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "5.0000",
            "1567.4500",
            "7837.25",
            "563.2800",
            "2816.40",
            "2816.40"
          ],
          "rowNumber": 1879433,
          "rowPosition": 1879434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879434\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "16974",
            "144883",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "5068.8400",
            "10137.68",
            "4624.6000",
            "9249.20",
            "9249.20"
          ],
          "rowNumber": 1879434,
          "rowPosition": 1879435,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879435\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "20551",
            "1",
            "58",
            "732",
            "10561",
            "254143",
            "379808",
            "78093",
            "37",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-10-13",
            "4.0000",
            "7933.4900",
            "31733.96",
            "7750.0000",
            "31000.00",
            "31000.00"
          ],
          "rowNumber": 1879435,
          "rowPosition": 1879436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78093\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879436\" violates the foreign key: for \"id_contrato\": values \"78093\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "240125",
            "379808",
            "78106",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "2059.0000",
            "4118.00",
            "1117.5000",
            "2235.00",
            "2235.00"
          ],
          "rowNumber": 1879436,
          "rowPosition": 1879437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879437\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "16974",
            "258026",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "8254.0000",
            "16508.00",
            "6233.9500",
            "12467.90",
            "12467.90"
          ],
          "rowNumber": 1879437,
          "rowPosition": 1879438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879438\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "235168",
            "379808",
            "78106",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "3641.9500",
            "7283.90",
            "3641.9500",
            "7283.90",
            "7283.90"
          ],
          "rowNumber": 1879438,
          "rowPosition": 1879439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879439\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3892",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "10.0000",
            "4308.0000",
            "43080.00",
            "2079.6600",
            "20796.60",
            "20796.60"
          ],
          "rowNumber": 1879439,
          "rowPosition": 1879440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879440\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "16974",
            "138217",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "4972.0500",
            "9944.10",
            "4642.7500",
            "9285.50",
            "9285.50"
          ],
          "rowNumber": 1879440,
          "rowPosition": 1879441,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879441\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "16974",
            "144881",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "3.0000",
            "9668.0800",
            "29004.23",
            "6233.9500",
            "18701.85",
            "18701.85"
          ],
          "rowNumber": 1879441,
          "rowPosition": 1879442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879442\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "241928",
            "379808",
            "78106",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "4788.0000",
            "9576.00",
            "4788.0000",
            "9576.00",
            "9576.00"
          ],
          "rowNumber": 1879442,
          "rowPosition": 1879443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879443\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "16974",
            "166729",
            "379808",
            "78099",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "2.0000",
            "8915.0000",
            "17830.00",
            "6252.8700",
            "12505.74",
            "12505.74"
          ],
          "rowNumber": 1879443,
          "rowPosition": 1879444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879444\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831017",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "3893",
            "379808",
            "78106",
            "889",
            "1831373",
            "2813",
            "2842",
            "2022",
            "2022-10-13",
            "6.0000",
            "3641.9500",
            "21851.70",
            "3641.9500",
            "21851.70",
            "21851.70"
          ],
          "rowNumber": 1879444,
          "rowPosition": 1879445,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879445\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "235168",
            "379836",
            "78106",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "2.0000",
            "3641.9500",
            "7283.90",
            "3641.9500",
            "7283.90",
            "7283.90"
          ],
          "rowNumber": 1879445,
          "rowPosition": 1879446,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879446\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "144028",
            "379836",
            "78106",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "6.0000",
            "2595.0000",
            "15570.00",
            "2595.0000",
            "15570.00",
            "15570.00"
          ],
          "rowNumber": 1879447,
          "rowPosition": 1879448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879448\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "240125",
            "379836",
            "78106",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "2.0000",
            "2059.0000",
            "4118.00",
            "1117.5000",
            "2235.00",
            "2235.00"
          ],
          "rowNumber": 1879448,
          "rowPosition": 1879449,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879449\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "10561",
            "128860",
            "379836",
            "78099",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1982.9600",
            "1982.96",
            "881.7300",
            "881.73",
            "881.73"
          ],
          "rowNumber": 1879449,
          "rowPosition": 1879450,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879450\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3794",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "2.0000",
            "1567.4500",
            "3134.90",
            "563.2800",
            "1126.56",
            "1126.56"
          ],
          "rowNumber": 1879452,
          "rowPosition": 1879453,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879453\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "22387",
            "270633",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "2.0000",
            "3560.0000",
            "7120.00",
            "1890.2300",
            "3780.46",
            "3780.46"
          ],
          "rowNumber": 1879453,
          "rowPosition": 1879454,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879454\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "10561",
            "59121",
            "379836",
            "78099",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1982.9600",
            "1982.96",
            "868.4800",
            "868.48",
            "868.48"
          ],
          "rowNumber": 1879454,
          "rowPosition": 1879455,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1879455\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "10561",
            "53476",
            "379836",
            "78099",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1982.9600",
            "1982.96",
            "874.5200",
            "874.52",
            "874.52"
          ],
          "rowNumber": 1880304,
          "rowPosition": 1880305,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880305\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "4307",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "5191.0000",
            "5191.00",
            "2838.3100",
            "2838.31",
            "2838.31"
          ],
          "rowNumber": 1880305,
          "rowPosition": 1880306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880306\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "10561",
            "125921",
            "379836",
            "78099",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1982.9600",
            "1982.96",
            "1040.0000",
            "1040.00",
            "1040.00"
          ],
          "rowNumber": 1880306,
          "rowPosition": 1880307,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880307\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3889",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "2.0000",
            "1434.0000",
            "2868.00",
            "609.9900",
            "1219.98",
            "1219.98"
          ],
          "rowNumber": 1880307,
          "rowPosition": 1880308,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880308\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3798",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "3.0000",
            "1654.0000",
            "4962.00",
            "541.5300",
            "1624.59",
            "1624.59"
          ],
          "rowNumber": 1880308,
          "rowPosition": 1880309,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880309\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "732",
            "10561",
            "134986",
            "379836",
            "78099",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1982.9600",
            "1982.96",
            "956.0000",
            "956.00",
            "956.00"
          ],
          "rowNumber": 1880309,
          "rowPosition": 1880310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880310\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "241928",
            "379836",
            "78106",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "3.0000",
            "4788.0000",
            "14364.00",
            "4788.0000",
            "14364.00",
            "14364.00"
          ],
          "rowNumber": 1880310,
          "rowPosition": 1880311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880311\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "60930",
            "1",
            "58",
            "411",
            "2849",
            "3892",
            "379836",
            "78099",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "4308.0000",
            "4308.00",
            "2079.6600",
            "2079.66",
            "2079.66"
          ],
          "rowNumber": 1880311,
          "rowPosition": 1880312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880312\" violates the foreign key: for \"id_contrato\": values \"78099\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831100",
            "99",
            "2",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "411",
            "2849",
            "3795",
            "379836",
            "78106",
            "889",
            "1831373",
            "2813",
            "3331",
            "2022",
            "2022-10-13",
            "1.0000",
            "1434.0000",
            "1434.00",
            "1306.8600",
            "1306.86",
            "1306.86"
          ],
          "rowNumber": 1880312,
          "rowPosition": 1880313,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880313\" violates the foreign key: for \"id_contrato\": values \"78106\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831096",
            "92",
            "1",
            "1",
            "856",
            "61940",
            "1",
            "51",
            "80",
            "20153",
            "124737",
            "381598",
            "78108",
            "889",
            "1831507",
            "3067",
            "2631",
            "2022",
            "2022-11-10",
            "0.0000",
            "35520.0000",
            "35520.00",
            "14920.0000",
            "14920.00",
            "14920.00"
          ],
          "rowNumber": 1890258,
          "rowPosition": 1890259,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890259\" violates the foreign key: for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831096",
            "92",
            "1",
            "1",
            "856",
            "61940",
            "1",
            "19",
            "628",
            "16622",
            "336403",
            "381598",
            "78108",
            "889",
            "1831992",
            "2584",
            "2631",
            "2022",
            "2022-11-10",
            "112.0000",
            "450.0000",
            "50400.00",
            "250.0000",
            "28000.00",
            "28000.00"
          ],
          "rowNumber": 1890259,
          "rowPosition": 1890260,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890260\" violates the foreign key: for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831096",
            "92",
            "1",
            "1",
            "856",
            "61940",
            "1",
            "19",
            "628",
            "16622",
            "336400",
            "381598",
            "78108",
            "889",
            "1831992",
            "2584",
            "2631",
            "2022",
            "2022-11-10",
            "384.0000",
            "245.0000",
            "94080.00",
            "120.0000",
            "46080.00",
            "46080.00"
          ],
          "rowNumber": 1890260,
          "rowPosition": 1890261,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890261\" violates the foreign key: for \"id_contrato\": values \"78108\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "20",
            "614",
            "3453",
            "63109",
            "382452",
            "78095",
            "889",
            "1831315",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "27.0000",
            "14.4900",
            "391.23",
            "14.4900",
            "391.23",
            "391.23"
          ],
          "rowNumber": 1890718,
          "rowPosition": 1890719,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890719\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "20",
            "614",
            "3453",
            "29731",
            "382452",
            "78095",
            "889",
            "1831315",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "25.0000",
            "43.9000",
            "1097.50",
            "43.9000",
            "1097.50",
            "1097.50"
          ],
          "rowNumber": 1890719,
          "rowPosition": 1890720,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890720\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "4",
            "410",
            "18369",
            "143378",
            "382452",
            "78095",
            "98",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "1.0000",
            "23.2200",
            "23.22",
            "23.0000",
            "23.00",
            "23.00"
          ],
          "rowNumber": 1890720,
          "rowPosition": 1890721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890721\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "52",
            "721",
            "5188",
            "9548",
            "382452",
            "78095",
            "196",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "2.0000",
            "459.9000",
            "919.80",
            "459.9000",
            "919.80",
            "919.80"
          ],
          "rowNumber": 1890721,
          "rowPosition": 1890722,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890722\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "38",
            "524",
            "474",
            "128863",
            "382452",
            "78095",
            "889",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "13.0000",
            "44.5000",
            "578.50",
            "44.5000",
            "578.50",
            "578.50"
          ],
          "rowNumber": 1890722,
          "rowPosition": 1890723,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890723\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "118",
            "72661",
            "1",
            "82",
            "647",
            "16197",
            "9622",
            "382452",
            "78095",
            "594",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "5.0000",
            "123.2000",
            "616.00",
            "123.2000",
            "616.00",
            "616.00"
          ],
          "rowNumber": 1890723,
          "rowPosition": 1890724,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890724\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "118",
            "72661",
            "1",
            "82",
            "647",
            "18445",
            "112684",
            "382452",
            "78095",
            "114",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "40.0000",
            "44.0000",
            "1760.00",
            "44.0000",
            "1760.00",
            "1760.00"
          ],
          "rowNumber": 1890724,
          "rowPosition": 1890725,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890725\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "118",
            "72661",
            "1",
            "82",
            "744",
            "15775",
            "28792",
            "382452",
            "78095",
            "889",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "1500.0000",
            "1.7000",
            "2550.00",
            "1.7000",
            "2550.00",
            "2550.00"
          ],
          "rowNumber": 1890725,
          "rowPosition": 1890726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890726\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "118",
            "72661",
            "1",
            "82",
            "647",
            "18483",
            "115381",
            "382452",
            "78095",
            "594",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "3.5000",
            "154.9900",
            "542.47",
            "154.9000",
            "542.15",
            "542.15"
          ],
          "rowNumber": 1890726,
          "rowPosition": 1890727,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890727\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "82",
            "647",
            "5309",
            "1995",
            "382452",
            "78095",
            "131",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "10.0000",
            "18.9000",
            "189.00",
            "18.9000",
            "189.00",
            "189.00"
          ],
          "rowNumber": 1890727,
          "rowPosition": 1890728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890728\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "52",
            "721",
            "5188",
            "9554",
            "382452",
            "78095",
            "196",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "2.0000",
            "189.5500",
            "379.10",
            "189.5500",
            "379.10",
            "379.10"
          ],
          "rowNumber": 1890728,
          "rowPosition": 1890729,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890729\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "72661",
            "1",
            "20",
            "245",
            "8531",
            "52516",
            "382452",
            "78095",
            "98",
            "1831189",
            "2658",
            "3043",
            "2022",
            "2022-11-22",
            "5.0000",
            "25.2500",
            "126.25",
            "25.0000",
            "125.00",
            "125.00"
          ],
          "rowNumber": 1890729,
          "rowPosition": 1890730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890730\" violates the foreign key: for \"id_contrato\": values \"78095\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43498",
            "5",
            "1831084",
            "81",
            "1",
            "1",
            "856",
            "67303",
            "1",
            "17",
            "175",
            "6976",
            "92592",
            "382526",
            "78111",
            "889",
            "1831350",
            "2613",
            "1859",
            "2022",
            "2022-11-23",
            "0.0000",
            "1743762.8900",
            "1743762.89",
            "1725001.8000",
            "1725001.80",
            "1725001.80"
          ],
          "rowNumber": 1891589,
          "rowPosition": 1891590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78111\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891590\" violates the foreign key: for \"id_contrato\": values \"78111\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "21",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "130",
            "1824",
            "98675",
            "382534",
            "78096",
            "26",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "367400.0000",
            "367400.00",
            "367400.0000",
            "367400.00",
            "367400.00"
          ],
          "rowNumber": 1891590,
          "rowPosition": 1891591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78096\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891591\" violates the foreign key: for \"id_contrato\": values \"78096\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44431",
            "21",
            "1831008",
            "5",
            "1",
            "1",
            "206",
            "7678",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "382519",
            "78088",
            "322",
            "1831697",
            "2669",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "15600000.0000",
            "15600000.00",
            "15600000.0000",
            "15600000.00",
            "15600000.00"
          ],
          "rowNumber": 1891591,
          "rowPosition": 1891592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78088\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891592\" violates the foreign key: for \"id_contrato\": values \"78088\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "739",
            "60777",
            "1",
            "66",
            "702",
            "4422",
            "93091",
            "381757",
            "78101",
            "889",
            "1831575",
            "2837",
            "3293",
            "2022",
            "2022-11-11",
            "0.0000",
            "1736280.0000",
            "1736280.00",
            "1187971.6800",
            "1187971.68",
            "1187971.68"
          ],
          "rowNumber": 1892285,
          "rowPosition": 1892286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78101\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892286\" violates the foreign key: for \"id_contrato\": values \"78101\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "355",
            "5672",
            "1",
            "66",
            "702",
            "4422",
            "93091",
            "381814",
            "78091",
            "889",
            "1831575",
            "2837",
            "3293",
            "2022",
            "2022-11-11",
            "0.0000",
            "979200.0000",
            "979200.00",
            "494985.6000",
            "494985.60",
            "494985.60"
          ],
          "rowNumber": 1892286,
          "rowPosition": 1892287,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78091\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892287\" violates the foreign key: for \"id_contrato\": values \"78091\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "14",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "67504",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "382219",
            "78084",
            "889",
            "1831731",
            "2954",
            "1760",
            "2022",
            "2022-11-18",
            "0.0000",
            "3960.0000",
            "3960.00",
            "3640.0000",
            "3640.00",
            "3640.00"
          ],
          "rowNumber": 1898197,
          "rowPosition": 1898198,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78084\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898198\" violates the foreign key: for \"id_contrato\": values \"78084\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44417",
            "14",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "61866",
            "1",
            "51",
            "75",
            "12402",
            "92901",
            "382233",
            "78090",
            "889",
            "1831498",
            "2594",
            "2839",
            "2022",
            "2022-11-18",
            "0.0000",
            "33000.0000",
            "33000.00",
            "28400.0000",
            "28400.00",
            "28400.00"
          ],
          "rowNumber": 1898205,
          "rowPosition": 1898206,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78090\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898206\" violates the foreign key: for \"id_contrato\": values \"78090\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43968",
            "2",
            "1831062",
            "56",
            "1",
            "1",
            "540",
            "31915",
            "1",
            "39",
            "130",
            "4614",
            "101259",
            "366256",
            "78107",
            "889",
            "1831812",
            "3065",
            "3330",
            "2022",
            "2022-03-30",
            "0.0000",
            "5898.0000",
            "5898.00",
            "5898.0000",
            "5898.00",
            "5898.00"
          ],
          "rowNumber": 1898919,
          "rowPosition": 1898920,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78107\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898920\" violates the foreign key: for \"id_contrato\": values \"78107\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44412",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "38",
            "60725",
            "1",
            "17",
            "379",
            "20263",
            "93263",
            "382141",
            "78102",
            "889",
            "1831370",
            "2594",
            "3043",
            "2022",
            "2022-11-18",
            "0.0000",
            "32778.7900",
            "32778.79",
            "32778.0000",
            "32778.00",
            "32778.00"
          ],
          "rowNumber": 1899585,
          "rowPosition": 1899586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78102\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899586\" violates the foreign key: for \"id_contrato\": values \"78102\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43507",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "835",
            "60507",
            "1",
            "51",
            "75",
            "14915",
            "151034",
            "382432",
            "78105",
            "889",
            "1831500",
            "2670",
            "2633",
            "2022",
            "2022-11-22",
            "0.0000",
            "23000.0000",
            "23000.00",
            "23000.0000",
            "23000.00",
            "23000.00"
          ],
          "rowNumber": 1899613,
          "rowPosition": 1899614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78105\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899614\" violates the foreign key: for \"id_contrato\": values \"78105\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831044",
            "36",
            "1",
            "1",
            "501",
            "54151",
            "5",
            "69",
            "740",
            "13114",
            "147581",
            "382495",
            "78085",
            "1174",
            "1831312",
            "2538",
            "2633",
            "2022",
            "2022-11-22",
            "600.0000",
            "24.4900",
            "14692.80",
            "24.4900",
            "14692.80",
            "14692.80"
          ],
          "rowNumber": 1899614,
          "rowPosition": 1899615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78085\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899615\" violates the foreign key: for \"id_contrato\": values \"78085\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43528",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "72",
            "19557",
            "1",
            "41",
            "806",
            "12292",
            "91082",
            "381753",
            "78087",
            "889",
            "1831800",
            "3136",
            "2925",
            "2022",
            "2022-11-11",
            "0.0000",
            "10510.0000",
            "10510.00",
            "10500.0000",
            "10500.00",
            "10500.00"
          ],
          "rowNumber": 1900334,
          "rowPosition": 1900335,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78087\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900335\" violates the foreign key: for \"id_contrato\": values \"78087\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 95
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 95,
    "tasks": 1
  },
  "valid": false
}