{
  "version": "4.38.0",
  "time": 410.554,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "cff4acc05060ae39195b1c50ed919a1a",
          "bytes": 58033236,
          "fields": 27,
          "rows": 1903820
        }
      },
      "time": 410.554,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43572",
            "14",
            "1831104",
            "100",
            "1",
            "1",
            "66",
            "29444",
            "1",
            "77",
            "73",
            "1880",
            "92488",
            "381275",
            "78190",
            "889",
            "1831761",
            "2872",
            "2080",
            "2022",
            "2022-11-04",
            "0.0000",
            "3180.0000",
            "3180.00",
            "3000.0000",
            "3000.00",
            "3000.00"
          ],
          "rowNumber": 1812564,
          "rowPosition": 1812565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812565\" violates the foreign key: for \"id_contrato\": values \"78190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "130",
            "21730",
            "235179",
            "381226",
            "78207",
            "889",
            "1831805",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "43134.0000",
            "43134.00",
            "43134.0000",
            "43134.00",
            "43134.00"
          ],
          "rowNumber": 1812566,
          "rowPosition": 1812567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812567\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "2012",
            "101258",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "111581.5200",
            "111581.52",
            "111581.5200",
            "111581.52",
            "111581.52"
          ],
          "rowNumber": 1812568,
          "rowPosition": 1812569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812569\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "2012",
            "98017",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "2648158.9600",
            "2648158.96",
            "2648158.9600",
            "2648158.96",
            "2648158.96"
          ],
          "rowNumber": 1812569,
          "rowPosition": 1812570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812570\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "12509",
            "141667",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "119700.0000",
            "119700.00",
            "119700.0000",
            "119700.00",
            "119700.00"
          ],
          "rowNumber": 1812570,
          "rowPosition": 1812571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812571\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "2012",
            "251219",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "1017480.0000",
            "1017480.00",
            "1017480.0000",
            "1017480.00",
            "1017480.00"
          ],
          "rowNumber": 1812571,
          "rowPosition": 1812572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812572\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "12509",
            "141671",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "15168.0000",
            "15168.00",
            "15168.0000",
            "15168.00",
            "15168.00"
          ],
          "rowNumber": 1812572,
          "rowPosition": 1812573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812573\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "282",
            "2012",
            "101257",
            "381226",
            "78207",
            "889",
            "1831812",
            "3065",
            "3043",
            "2022",
            "2022-11-04",
            "0.0000",
            "26752.9200",
            "26752.92",
            "26752.9200",
            "26752.92",
            "26752.92"
          ],
          "rowNumber": 1812573,
          "rowPosition": 1812574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812574\" violates the foreign key: for \"id_contrato\": values \"78207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831015",
            "14",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "378619",
            "78188",
            "190",
            "1831313",
            "2928",
            "1836",
            "2022",
            "2022-09-26",
            "30000.0000",
            "5.9700",
            "179058.00",
            "5.9700",
            "179058.00",
            "179058.00"
          ],
          "rowNumber": 1812653,
          "rowPosition": 1812654,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812654\" violates the foreign key: for \"id_contrato\": values \"78188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831015",
            "14",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "378619",
            "78188",
            "190",
            "1831313",
            "2928",
            "1836",
            "2022",
            "2022-09-26",
            "15000.0000",
            "4.1100",
            "61623.00",
            "4.1100",
            "61623.00",
            "61623.00"
          ],
          "rowNumber": 1812654,
          "rowPosition": 1812655,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812655\" violates the foreign key: for \"id_contrato\": values \"78188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43537",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "66",
            "55805",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "381971",
            "78210",
            "889",
            "1831520",
            "2670",
            "2413",
            "2022",
            "2022-11-16",
            "0.0000",
            "2823.3300",
            "2823.33",
            "2823.3300",
            "2823.33",
            "2823.33"
          ],
          "rowNumber": 1813450,
          "rowPosition": 1813451,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78210\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813451\" violates the foreign key: for \"id_contrato\": values \"78210\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43568",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "68116",
            "1",
            "46",
            "10",
            "7789",
            "73100",
            "380883",
            "78199",
            "889",
            "1831846",
            "3078",
            "3043",
            "2022",
            "2022-10-26",
            "105.0000",
            "1048.9900",
            "110143.95",
            "514.1700",
            "53987.47",
            "53987.47"
          ],
          "rowNumber": 1813610,
          "rowPosition": 1813611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813611\" violates the foreign key: for \"id_contrato\": values \"78199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "263364",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "250.0000",
            "155.8600",
            "38965.00",
            "155.8600",
            "38965.00",
            "38965.00"
          ],
          "rowNumber": 1815264,
          "rowPosition": 1815265,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815265\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21889",
            "192740",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "10.0000",
            "429.8500",
            "4298.50",
            "429.8500",
            "4298.50",
            "4298.50"
          ],
          "rowNumber": 1815265,
          "rowPosition": 1815266,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815266\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "265895",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "20.0000",
            "1012.6100",
            "20252.20",
            "1012.6100",
            "20252.20",
            "20252.20"
          ],
          "rowNumber": 1815266,
          "rowPosition": 1815267,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815267\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "335962",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "1000.0000",
            "10.3500",
            "10350.00",
            "10.3500",
            "10350.00",
            "10350.00"
          ],
          "rowNumber": 1815267,
          "rowPosition": 1815268,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815268\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "263372",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "730.0000",
            "367.0200",
            "267924.60",
            "367.0200",
            "267924.60",
            "267924.60"
          ],
          "rowNumber": 1815268,
          "rowPosition": 1815269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815269\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21815",
            "339208",
            "382967",
            "78206",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "1000.0000",
            "258.2700",
            "258270.00",
            "258.2700",
            "258270.00",
            "258270.00"
          ],
          "rowNumber": 1815269,
          "rowPosition": 1815270,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815270\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "130",
            "21730",
            "334463",
            "382967",
            "78206",
            "889",
            "1831805",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "37.0000",
            "4748.6100",
            "175698.57",
            "4748.6100",
            "175698.57",
            "175698.57"
          ],
          "rowNumber": 1815270,
          "rowPosition": 1815271,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815271\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "710",
            "7497",
            "334679",
            "382967",
            "78206",
            "889",
            "1831805",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "285.0000",
            "652.3100",
            "185908.35",
            "652.3100",
            "185908.35",
            "185908.35"
          ],
          "rowNumber": 1815271,
          "rowPosition": 1815272,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815272\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831084",
            "81",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "130",
            "21730",
            "339215",
            "382967",
            "78206",
            "889",
            "1831805",
            "3067",
            "1859",
            "2022",
            "2022-11-28",
            "5.0000",
            "270.5200",
            "1352.60",
            "270.5200",
            "1352.60",
            "1352.60"
          ],
          "rowNumber": 1815272,
          "rowPosition": 1815273,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815273\" violates the foreign key: for \"id_contrato\": values \"78206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "37781",
            "1",
            "17",
            "175",
            "4343",
            "102686",
            "381938",
            "78194",
            "889",
            "1831370",
            "2594",
            "2925",
            "2022",
            "2022-11-16",
            "0.0000",
            "513768.9900",
            "513768.99",
            "477291.3900",
            "477291.39",
            "477291.39"
          ],
          "rowNumber": 1817327,
          "rowPosition": 1817328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817328\" violates the foreign key: for \"id_contrato\": values \"78194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "1",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "72817",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "383007",
            "46296",
            "889",
            "1831808",
            "2806",
            "1760",
            "2022",
            "2022-11-28",
            "0.0000",
            "16000.0000",
            "16000.00",
            "16000.0000",
            "16000.00",
            "16000.00"
          ],
          "rowNumber": 1817831,
          "rowPosition": 1817832,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72817\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1817832\" violates the foreign key: for \"id_contratado\": values \"72817\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43513",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31560",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "381128",
            "78191",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-03",
            "0.0000",
            "5917.6000",
            "5917.60",
            "5000.0000",
            "5000.00",
            "5000.00"
          ],
          "rowNumber": 1819724,
          "rowPosition": 1819725,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819725\" violates the foreign key: for \"id_contrato\": values \"78191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "69038",
            "1",
            "89",
            "643",
            "3288",
            "147833",
            "381421",
            "78187",
            "889",
            "1831991",
            "2924",
            "3043",
            "2022",
            "2022-11-08",
            "4.0000",
            "3470.1700",
            "13880.68",
            "4275.0000",
            "17100.00",
            "17100.00"
          ],
          "rowNumber": 1822447,
          "rowPosition": 1822448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822448\" violates the foreign key: for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "69038",
            "1",
            "89",
            "643",
            "3288",
            "160007",
            "381421",
            "78187",
            "889",
            "1831991",
            "2924",
            "3043",
            "2022",
            "2022-11-08",
            "4.0000",
            "4987.0000",
            "19948.00",
            "4275.0000",
            "17100.00",
            "17100.00"
          ],
          "rowNumber": 1822448,
          "rowPosition": 1822449,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822449\" violates the foreign key: for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "69038",
            "1",
            "89",
            "643",
            "3288",
            "139057",
            "381421",
            "78187",
            "889",
            "1831991",
            "2924",
            "3043",
            "2022",
            "2022-11-08",
            "4.0000",
            "4368.0000",
            "17472.00",
            "4275.0000",
            "17100.00",
            "17100.00"
          ],
          "rowNumber": 1822449,
          "rowPosition": 1822450,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822450\" violates the foreign key: for \"id_contrato\": values \"78187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44430",
            "17",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "28939",
            "1",
            "89",
            "176",
            "17874",
            "385844",
            "382263",
            "78208",
            "889",
            "1831991",
            "3018",
            "2839",
            "2022",
            "2022-11-21",
            "6.0000",
            "8450.0000",
            "50700.00",
            "8450.0000",
            "50700.00",
            "50700.00"
          ],
          "rowNumber": 1852167,
          "rowPosition": 1852168,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852168\" violates the foreign key: for \"id_contrato\": values \"78208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "72640",
            "1",
            "3",
            "237",
            "15147",
            "151259",
            "382078",
            "78198",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-11-17",
            "700.0000",
            "3700.0000",
            "2590000.00",
            "3700.0000",
            "2590000.00",
            "2590000.00"
          ],
          "rowNumber": 1853771,
          "rowPosition": 1853772,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853772\" violates the foreign key: for \"id_contrato\": values \"78198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "72640",
            "1",
            "3",
            "237",
            "6813",
            "305570",
            "382078",
            "78198",
            "889",
            "1831295",
            "2584",
            "1760",
            "2022",
            "2022-11-17",
            "700.0000",
            "311.0000",
            "217700.00",
            "311.0000",
            "217700.00",
            "217700.00"
          ],
          "rowNumber": 1853772,
          "rowPosition": 1853773,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853773\" violates the foreign key: for \"id_contrato\": values \"78198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "396",
            "1",
            "77",
            "183",
            "9650",
            "92801",
            "382066",
            "78211",
            "889",
            "1831780",
            "3136",
            "3043",
            "2022",
            "2022-11-17",
            "0.0000",
            "80974.2000",
            "80974.20",
            "80974.2000",
            "80974.20",
            "80974.20"
          ],
          "rowNumber": 1858175,
          "rowPosition": 1858176,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78211\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858176\" violates the foreign key: for \"id_contrato\": values \"78211\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43533",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60415",
            "1",
            "3",
            "627",
            "19215",
            "335718",
            "382060",
            "78202",
            "889",
            "1831295",
            "2611",
            "3331",
            "2022",
            "2022-11-17",
            "2.0000",
            "41519.5800",
            "83039.16",
            "41519.5800",
            "83039.16",
            "83039.16"
          ],
          "rowNumber": 1858178,
          "rowPosition": 1858179,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858179\" violates the foreign key: for \"id_contrato\": values \"78202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43536",
            "2",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "11586",
            "1",
            "77",
            "533",
            "17583",
            "252797",
            "380991",
            "78195",
            "889",
            "1831554",
            "2738",
            "2838",
            "2022",
            "2022-10-27",
            "0.0000",
            "99840.0000",
            "99840.00",
            "99840.0000",
            "99840.00",
            "99840.00"
          ],
          "rowNumber": 1859385,
          "rowPosition": 1859386,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859386\" violates the foreign key: for \"id_contrato\": values \"78195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "241",
            "13878",
            "1",
            "77",
            "808",
            "4383",
            "91626",
            "382368",
            "78197",
            "889",
            "1899033",
            "2869",
            "3043",
            "2022",
            "2022-11-21",
            "0.0000",
            "21900.0000",
            "21900.00",
            "16060.0000",
            "16060.00",
            "16060.00"
          ],
          "rowNumber": 1859755,
          "rowPosition": 1859756,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859756\" violates the foreign key: for \"id_contrato\": values \"78197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "241",
            "13878",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "382368",
            "78197",
            "889",
            "1831737",
            "2869",
            "3043",
            "2022",
            "2022-11-21",
            "0.0000",
            "81760.0000",
            "81760.00",
            "87600.0000",
            "87600.00",
            "87600.00"
          ],
          "rowNumber": 1859756,
          "rowPosition": 1859757,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859757\" violates the foreign key: for \"id_contrato\": values \"78197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50301",
            "1",
            "1831047",
            "37",
            "1",
            "1",
            "66",
            "15201",
            "1",
            "39",
            "130",
            "1824",
            "141584",
            "377232",
            "78185",
            "889",
            "1831805",
            "3067",
            "3044",
            "2021",
            "2022-09-08",
            "0.0000",
            "17945.4000",
            "17945.40",
            "17945.4000",
            "17945.40",
            "17945.40"
          ],
          "rowNumber": 1878525,
          "rowPosition": 1878526,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78185\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1878526\" violates the foreign key: for \"id_contrato\": values \"78185\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "18849",
            "1",
            "51",
            "75",
            "14915",
            "224982",
            "379548",
            "78192",
            "889",
            "1831500",
            "2670",
            "1858",
            "2022",
            "2022-10-10",
            "0.0000",
            "89000.0000",
            "89000.00",
            "65000.0000",
            "65000.00",
            "65000.00"
          ],
          "rowNumber": 1883819,
          "rowPosition": 1883820,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883820\" violates the foreign key: for \"id_contrato\": values \"78192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "18849",
            "1",
            "51",
            "75",
            "14915",
            "194792",
            "379548",
            "78192",
            "889",
            "1831500",
            "2670",
            "1858",
            "2022",
            "2022-10-10",
            "0.0000",
            "250800.0000",
            "250800.00",
            "237600.0000",
            "237600.00",
            "237600.00"
          ],
          "rowNumber": 1883820,
          "rowPosition": 1883821,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883821\" violates the foreign key: for \"id_contrato\": values \"78192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "2",
            "1831041",
            "41",
            "1",
            "1",
            "147",
            "55201",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "382194",
            "78200",
            "322",
            "1831697",
            "2932",
            "2689",
            "2022",
            "2022-11-18",
            "0.0000",
            "156000.0000",
            "156000.00",
            "84000.0000",
            "84000.00",
            "84000.00"
          ],
          "rowNumber": 1889634,
          "rowPosition": 1889635,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1889635\" violates the foreign key: for \"id_contrato\": values \"78200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831105",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "66054",
            "381721",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3294",
            "2022",
            "2022-11-10",
            "16.0000",
            "66.9100",
            "1070.56",
            "50.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1892183,
          "rowPosition": 1892184,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892184\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831105",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "66055",
            "381721",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3294",
            "2022",
            "2022-11-10",
            "22.0000",
            "80.0000",
            "1760.00",
            "26.8500",
            "590.70",
            "590.70"
          ],
          "rowNumber": 1892184,
          "rowPosition": 1892185,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892185\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831105",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "131830",
            "381721",
            "78205",
            "1859",
            "1831373",
            "2796",
            "3294",
            "2022",
            "2022-11-10",
            "50.0000",
            "148.6600",
            "7433.00",
            "62.9500",
            "3147.50",
            "3147.50"
          ],
          "rowNumber": 1892185,
          "rowPosition": 1892186,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892186\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831105",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "45853",
            "381721",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3294",
            "2022",
            "2022-11-10",
            "47.0000",
            "126.2200",
            "5932.34",
            "27.8000",
            "1306.60",
            "1306.60"
          ],
          "rowNumber": 1892186,
          "rowPosition": 1892187,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892187\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831105",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "48120",
            "381721",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3294",
            "2022",
            "2022-11-10",
            "34.0000",
            "64.5000",
            "2193.00",
            "27.0000",
            "918.00",
            "918.00"
          ],
          "rowNumber": 1892187,
          "rowPosition": 1892188,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892188\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "2",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "130",
            "20348",
            "98672",
            "382539",
            "78186",
            "889",
            "1831812",
            "3135",
            "2046",
            "2022",
            "2022-11-23",
            "0.0000",
            "7966956.0000",
            "7966956.00",
            "7966956.0000",
            "7966956.00",
            "7966956.00"
          ],
          "rowNumber": 1893329,
          "rowPosition": 1893330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78186\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893330\" violates the foreign key: for \"id_contrato\": values \"78186\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "80",
            "621",
            "21585",
            "181759",
            "382593",
            "78196",
            "1071",
            "1831400",
            "2923",
            "3331",
            "2022",
            "2022-11-23",
            "1060.0000",
            "72.8600",
            "77231.60",
            "72.8600",
            "77231.60",
            "77231.60"
          ],
          "rowNumber": 1894262,
          "rowPosition": 1894263,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894263\" violates the foreign key: for \"id_contrato\": values \"78196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "23776",
            "1",
            "80",
            "621",
            "21585",
            "170091",
            "382593",
            "78201",
            "1071",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-11-23",
            "1250.0000",
            "8.9500",
            "11187.50",
            "8.9500",
            "11187.50",
            "11187.50"
          ],
          "rowNumber": 1894263,
          "rowPosition": 1894264,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894264\" violates the foreign key: for \"id_contrato\": values \"78201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43549",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "876",
            "56196",
            "1",
            "51",
            "382",
            "9755",
            "283650",
            "379968",
            "78204",
            "889",
            "1831498",
            "2670",
            "2082",
            "2022",
            "2022-10-14",
            "0.0000",
            "225501.7600",
            "225501.76",
            "225501.7600",
            "225501.76",
            "225501.76"
          ],
          "rowNumber": 1898984,
          "rowPosition": 1898985,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898985\" violates the foreign key: for \"id_contrato\": values \"78204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "69086",
            "381619",
            "78205",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "1920.0000",
            "0.6400",
            "1228.80",
            "0.6300",
            "1209.60",
            "1209.60"
          ],
          "rowNumber": 1900218,
          "rowPosition": 1900219,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900219\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "56904",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "31.0000",
            "50.4000",
            "1562.40",
            "38.7000",
            "1199.70",
            "1199.70"
          ],
          "rowNumber": 1900219,
          "rowPosition": 1900220,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900220\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "15080",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "83.0000",
            "94.5400",
            "7846.82",
            "20.8600",
            "1731.38",
            "1731.38"
          ],
          "rowNumber": 1900221,
          "rowPosition": 1900222,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900222\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "99019",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "49200.0000",
            "0.2500",
            "12300.00",
            "0.0900",
            "4428.00",
            "4428.00"
          ],
          "rowNumber": 1900222,
          "rowPosition": 1900223,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900223\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "40990",
            "381619",
            "78184",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "10800.0000",
            "0.9800",
            "10584.00",
            "0.9500",
            "10260.00",
            "10260.00"
          ],
          "rowNumber": 1900223,
          "rowPosition": 1900224,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900224\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "143898",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "5000.0000",
            "0.6600",
            "3300.00",
            "0.5000",
            "2500.00",
            "2500.00"
          ],
          "rowNumber": 1900224,
          "rowPosition": 1900225,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900225\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "45852",
            "381619",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "112.0000",
            "70.2500",
            "7868.00",
            "25.0000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1900225,
          "rowPosition": 1900226,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900226\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "66055",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "9070.0000",
            "80.0000",
            "725600.00",
            "26.8500",
            "243529.50",
            "243529.50"
          ],
          "rowNumber": 1900226,
          "rowPosition": 1900227,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900227\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "15920",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "3.0000",
            "43.2000",
            "129.60",
            "43.2000",
            "129.60",
            "129.60"
          ],
          "rowNumber": 1900227,
          "rowPosition": 1900228,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900228\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "140831",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "2200.0000",
            "2.2500",
            "4950.00",
            "2.2500",
            "4950.00",
            "4950.00"
          ],
          "rowNumber": 1900228,
          "rowPosition": 1900229,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900229\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "173263",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "3000.0000",
            "1.0300",
            "3090.00",
            "0.8000",
            "2400.00",
            "2400.00"
          ],
          "rowNumber": 1900229,
          "rowPosition": 1900230,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900230\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "98857",
            "381619",
            "78205",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "12000.0000",
            "0.2500",
            "3000.00",
            "0.1200",
            "1440.00",
            "1440.00"
          ],
          "rowNumber": 1900230,
          "rowPosition": 1900231,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900231\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "131830",
            "381619",
            "78205",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "2.0000",
            "148.6600",
            "297.32",
            "62.9500",
            "125.90",
            "125.90"
          ],
          "rowNumber": 1900231,
          "rowPosition": 1900232,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900232\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "100109",
            "381619",
            "78205",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "208.0000",
            "60.0000",
            "12480.00",
            "32.6100",
            "6782.88",
            "6782.88"
          ],
          "rowNumber": 1900232,
          "rowPosition": 1900233,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900233\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "52313",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "4000.0000",
            "1.3500",
            "5400.00",
            "0.2200",
            "880.00",
            "880.00"
          ],
          "rowNumber": 1900233,
          "rowPosition": 1900234,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900234\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "41930",
            "381619",
            "78184",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "8000.0000",
            "0.3400",
            "2720.00",
            "0.2000",
            "1600.00",
            "1600.00"
          ],
          "rowNumber": 1900234,
          "rowPosition": 1900235,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900235\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "45853",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "9120.0000",
            "126.2200",
            "1151126.40",
            "27.8000",
            "253536.00",
            "253536.00"
          ],
          "rowNumber": 1900235,
          "rowPosition": 1900236,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900236\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "10699",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "107.0000",
            "70.2500",
            "7516.75",
            "40.0000",
            "4280.00",
            "4280.00"
          ],
          "rowNumber": 1900236,
          "rowPosition": 1900237,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900237\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "45873",
            "381619",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "260.0000",
            "57.8600",
            "15043.60",
            "20.0000",
            "5200.00",
            "5200.00"
          ],
          "rowNumber": 1900237,
          "rowPosition": 1900238,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900238\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "48120",
            "381619",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "60.0000",
            "64.5000",
            "3870.00",
            "27.0000",
            "1620.00",
            "1620.00"
          ],
          "rowNumber": 1900238,
          "rowPosition": 1900239,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900239\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "143820",
            "381619",
            "78183",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "20.0000",
            "65.0000",
            "1300.00",
            "23.0000",
            "460.00",
            "460.00"
          ],
          "rowNumber": 1900239,
          "rowPosition": 1900240,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900240\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "46490",
            "381619",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "436.0000",
            "38.5100",
            "16790.36",
            "20.0000",
            "8720.00",
            "8720.00"
          ],
          "rowNumber": 1900240,
          "rowPosition": 1900241,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900241\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "55169",
            "1",
            "58",
            "732",
            "18473",
            "100010",
            "381619",
            "78184",
            "1859",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "135.0000",
            "70.2500",
            "9483.75",
            "25.0000",
            "3375.00",
            "3375.00"
          ],
          "rowNumber": 1900241,
          "rowPosition": 1900242,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900242\" violates the foreign key: for \"id_contrato\": values \"78184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "100112",
            "381619",
            "78183",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "7840.0000",
            "0.8000",
            "6272.00",
            "0.3000",
            "2352.00",
            "2352.00"
          ],
          "rowNumber": 1900242,
          "rowPosition": 1900243,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900243\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "77246",
            "381619",
            "78183",
            "848",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-10",
            "2.0000",
            "120.0000",
            "240.00",
            "120.0000",
            "240.00",
            "240.00"
          ],
          "rowNumber": 1900245,
          "rowPosition": 1900246,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900246\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831105",
            "91",
            "2",
            "1",
            "66",
            "20079",
            "1",
            "77",
            "533",
            "20181",
            "91916",
            "382190",
            "78209",
            "889",
            "1831527",
            "2738",
            "3042",
            "2022",
            "2022-11-18",
            "0.0000",
            "277777.5000",
            "277777.50",
            "277777.5000",
            "277777.50",
            "277777.50"
          ],
          "rowNumber": 1901361,
          "rowPosition": 1901362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901362\" violates the foreign key: for \"id_contrato\": values \"78209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44430",
            "2",
            "1831046",
            "43",
            "1",
            "1",
            "206",
            "57991",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "382467",
            "78193",
            "1174",
            "1831312",
            "2538",
            "2696",
            "2022",
            "2022-11-22",
            "393.0000",
            "28.4900",
            "11194.61",
            "28.4900",
            "11194.60",
            "11194.60"
          ],
          "rowNumber": 1901364,
          "rowPosition": 1901365,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901365\" violates the foreign key: for \"id_contrato\": values \"78193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831085",
            "79",
            "1",
            "1",
            "876",
            "33413",
            "1",
            "9",
            "576",
            "17494",
            "89820",
            "382450",
            "78189",
            "889",
            "1831691",
            "2736",
            "2924",
            "2022",
            "2022-11-22",
            "0.0000",
            "42520.0000",
            "42520.00",
            "42000.0000",
            "42000.00",
            "42000.00"
          ],
          "rowNumber": 1901367,
          "rowPosition": 1901368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901368\" violates the foreign key: for \"id_contrato\": values \"78189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "19463",
            "1",
            "58",
            "732",
            "18473",
            "143821",
            "381711",
            "78205",
            "1859",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-10",
            "11.0000",
            "136.2600",
            "1498.86",
            "68.9500",
            "758.45",
            "758.45"
          ],
          "rowNumber": 1902026,
          "rowPosition": 1902027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902027\" violates the foreign key: for \"id_contrato\": values \"78205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "15080",
            "381711",
            "78183",
            "1859",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-10",
            "32.0000",
            "94.5400",
            "3025.28",
            "20.8600",
            "667.52",
            "667.52"
          ],
          "rowNumber": 1902027,
          "rowPosition": 1902028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902028\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43988",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "15667",
            "1",
            "58",
            "732",
            "18473",
            "130497",
            "381711",
            "78183",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-10",
            "1000.0000",
            "0.6000",
            "600.00",
            "0.1900",
            "190.00",
            "190.00"
          ],
          "rowNumber": 1902028,
          "rowPosition": 1902029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902029\" violates the foreign key: for \"id_contrato\": values \"78183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "68921",
            "1",
            "3",
            "237",
            "7897",
            "251963",
            "382497",
            "78203",
            "889",
            "1831295",
            "2611",
            "2631",
            "2022",
            "2022-11-22",
            "2.0000",
            "1194977.0200",
            "2389954.04",
            "521000.0000",
            "1042000.00",
            "1042000.00"
          ],
          "rowNumber": 1902257,
          "rowPosition": 1902258,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902258\" violates the foreign key: for \"id_contrato\": values \"78203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 80
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 80,
    "tasks": 1
  },
  "valid": false
}