{
  "version": "4.38.0",
  "time": 515.216,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_despesa_2022",
        "title": "Despesa 2022",
        "path": "data/ft_despesa_2022.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_categ_econ",
              "title": "Categoria Econômica da Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo",
              "title": "Grupo de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_modalidade_aplic",
              "title": "Modalidade de Aplicação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_subfuncao",
              "title": "Subfunção - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedencia",
              "title": "Procedência - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_documento",
              "title": "Tipo de Documento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "tp_operacao",
              "title": "Tipo Operação - Chave Origem",
              "type": "string",
              "format": "default",
              "constraints": {
                "enum": [
                  "1",
                  "2"
                ]
              }
            },
            {
              "name": "cd_documento",
              "title": "Documento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "cd_evento",
              "title": "Evento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_anomes",
              "title": "Ano e Mês",
              "type": "string",
              "format": "default",
              "bareNumber": true,
              "notes": [
                "O tipo yearmonth somente aceita representação YYYY-MM (ie. com hífen)"
              ]
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_empenhado",
              "title": "Valor Empenhado",
              "description": "Valor do orçamento reservado para fazer face a compromisso formalmente assumido com fornecedor ou credor.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liquidado",
              "title": "Valor Liquidado",
              "description": "Valor que o fornecedor ou credor tem direito a receber referente a produto ou serviço devidamente entregue ou prestado.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_pago",
              "title": "Valor Pago",
              "description": "- > \nValor referente aos pagamentos efetuados através de movimentações bancárias, escriturais e apropriação contábil da\ndespesa. O efetivo pagamento pode estar pendente de transmissão ao banco e/ou sujeito a compensação bancária.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            },
            {
              "fields": [
                "id_tipo_documento"
              ],
              "reference": {
                "fields": [
                  "id_tipo_documento"
                ],
                "resource": "dm_tipo_documento"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_categ_econ"
              ],
              "reference": {
                "fields": [
                  "id_categ_econ"
                ],
                "resource": "dm_categ_econ"
              }
            },
            {
              "fields": [
                "id_grupo"
              ],
              "reference": {
                "fields": [
                  "id_grupo"
                ],
                "resource": "dm_grupo_desp"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_2022"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_subfuncao"
              ],
              "reference": {
                "fields": [
                  "id_subfuncao"
                ],
                "resource": "dm_subfuncao_desp"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_modalidade_aplic"
              ],
              "reference": {
                "fields": [
                  "id_modalidade_aplic"
                ],
                "resource": "dm_modalidade_aplic"
              }
            },
            {
              "fields": [
                "id_procedencia"
              ],
              "reference": {
                "fields": [
                  "id_procedencia"
                ],
                "resource": "dm_procedencia"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_despesa_2022"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "31878394e18f0082ec93276779a8ce0b",
          "bytes": 46388551,
          "fields": 24,
          "rows": 2930896
        }
      },
      "time": 515.216,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "498",
            "2",
            "53",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "288567224.00"
          ],
          "rowNumber": 2902903,
          "rowPosition": 2902904,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902904\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "498",
            "2",
            "55",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "290204740.57"
          ],
          "rowNumber": 2902904,
          "rowPosition": 2902905,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902905\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "498",
            "2",
            "57",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "121004368.26"
          ],
          "rowNumber": 2902905,
          "rowPosition": 2902906,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902906\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649357",
            "498",
            "2",
            "58",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "17929597.39"
          ],
          "rowNumber": 2902906,
          "rowPosition": 2902907,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902907\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "498",
            "2",
            "60",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "292326771.39"
          ],
          "rowNumber": 2902907,
          "rowPosition": 2902908,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902908\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "498",
            "2",
            "62",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "121717767.98"
          ],
          "rowNumber": 2902908,
          "rowPosition": 2902909,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902909\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "498",
            "2",
            "64",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "293773547.13"
          ],
          "rowNumber": 2902909,
          "rowPosition": 2902910,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902910\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "498",
            "2",
            "66",
            "616185",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "122372411.56"
          ],
          "rowNumber": 2902910,
          "rowPosition": 2902911,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902911\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "498",
            "2",
            "52",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "161537074.04"
          ],
          "rowNumber": 2902911,
          "rowPosition": 2902912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902912\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "498",
            "2",
            "54",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "163273486.32"
          ],
          "rowNumber": 2902912,
          "rowPosition": 2902913,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902913\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "498",
            "2",
            "56",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "52805332.03"
          ],
          "rowNumber": 2902913,
          "rowPosition": 2902914,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902914\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "498",
            "2",
            "59",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "165352507.00"
          ],
          "rowNumber": 2902914,
          "rowPosition": 2902915,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902915\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "498",
            "2",
            "61",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "53371345.52"
          ],
          "rowNumber": 2902915,
          "rowPosition": 2902916,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902916\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "498",
            "2",
            "63",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "167012530.77"
          ],
          "rowNumber": 2902916,
          "rowPosition": 2902917,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902917\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44470",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "498",
            "2",
            "65",
            "616186",
            "202212",
            "2022",
            "0.00",
            "0.00",
            "53916062.37"
          ],
          "rowNumber": 2902917,
          "rowPosition": 2902918,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2902918\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "42",
            "466",
            "3174",
            "58",
            "130",
            "1950",
            "3940",
            "14390",
            "56496",
            "93",
            "4247",
            "1622564",
            "13650256",
            "1",
            "2",
            "17",
            "502001",
            "202212",
            "2022",
            "550618035.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914235,
          "rowPosition": 2914236,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3174\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914236\" violates the foreign key: for \"id_item\": values \"3174\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1201",
            "503002",
            "202212",
            "2022",
            "0.00",
            "122372411.56",
            "0.00"
          ],
          "rowNumber": 2914236,
          "rowPosition": 2914237,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914237\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1200",
            "503002",
            "202212",
            "2022",
            "0.00",
            "141717767.98",
            "0.00"
          ],
          "rowNumber": 2914237,
          "rowPosition": 2914238,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914238\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1186",
            "503002",
            "202212",
            "2022",
            "0.00",
            "288567224.00",
            "0.00"
          ],
          "rowNumber": 2914238,
          "rowPosition": 2914239,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914239\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649357",
            "510",
            "2",
            "1187",
            "503002",
            "202212",
            "2022",
            "0.00",
            "17929597.39",
            "0.00"
          ],
          "rowNumber": 2914239,
          "rowPosition": 2914240,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914240\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1191",
            "503002",
            "202212",
            "2022",
            "0.00",
            "292326771.39",
            "0.00"
          ],
          "rowNumber": 2914240,
          "rowPosition": 2914241,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914241\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1189",
            "503002",
            "202212",
            "2022",
            "0.00",
            "290204740.57",
            "0.00"
          ],
          "rowNumber": 2914241,
          "rowPosition": 2914242,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914242\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1193",
            "503002",
            "202212",
            "2022",
            "0.00",
            "293773547.13",
            "0.00"
          ],
          "rowNumber": 2914242,
          "rowPosition": 2914243,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914243\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1198",
            "503002",
            "202212",
            "2022",
            "0.00",
            "121004368.26",
            "0.00"
          ],
          "rowNumber": 2914243,
          "rowPosition": 2914244,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914244\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1011",
            "504001",
            "202212",
            "2022",
            "290204740.57",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914244,
          "rowPosition": 2914245,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914245\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1013",
            "504001",
            "202212",
            "2022",
            "292326771.39",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914245,
          "rowPosition": 2914246,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914246\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1015",
            "504001",
            "202212",
            "2022",
            "293773547.13",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914246,
          "rowPosition": 2914247,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914247\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "558",
            "2",
            "1017",
            "504001",
            "202212",
            "2022",
            "121717767.98",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914247,
          "rowPosition": 2914248,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914248\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "558",
            "2",
            "1019",
            "504001",
            "202212",
            "2022",
            "122372411.56",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914248,
          "rowPosition": 2914249,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914249\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "566",
            "2",
            "347",
            "537003",
            "202212",
            "2022",
            "0.00",
            "-20000000.00",
            "0.00"
          ],
          "rowNumber": 2914249,
          "rowPosition": 2914250,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914250\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "1",
            "2",
            "168",
            "502001",
            "202212",
            "2022",
            "288567224.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914250,
          "rowPosition": 2914251,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914251\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "1",
            "2",
            "170",
            "502001",
            "202212",
            "2022",
            "121004368.26",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914964,
          "rowPosition": 2914965,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914965\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649357",
            "1",
            "2",
            "171",
            "502001",
            "202212",
            "2022",
            "17929597.39",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914965,
          "rowPosition": 2914966,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914966\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "42",
            "520",
            "3175",
            "44",
            "140",
            "1953",
            "3976",
            "14390",
            "56685",
            "93",
            "4247",
            "1202650",
            "13650414",
            "1",
            "2",
            "18",
            "502001",
            "202212",
            "2022",
            "591291191.59",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914966,
          "rowPosition": 2914967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3175\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914967\" violates the foreign key: for \"id_item\": values \"3175\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1195",
            "503006",
            "202212",
            "2022",
            "0.00",
            "53371345.52",
            "0.00"
          ],
          "rowNumber": 2914967,
          "rowPosition": 2914968,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914968\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1188",
            "503006",
            "202212",
            "2022",
            "0.00",
            "163273486.32",
            "0.00"
          ],
          "rowNumber": 2914968,
          "rowPosition": 2914969,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914969\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1190",
            "503006",
            "202212",
            "2022",
            "0.00",
            "165352507.00",
            "0.00"
          ],
          "rowNumber": 2914969,
          "rowPosition": 2914970,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914970\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1192",
            "503006",
            "202212",
            "2022",
            "0.00",
            "167012530.77",
            "0.00"
          ],
          "rowNumber": 2914970,
          "rowPosition": 2914971,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914971\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1194",
            "503006",
            "202212",
            "2022",
            "0.00",
            "52805332.03",
            "0.00"
          ],
          "rowNumber": 2914971,
          "rowPosition": 2914972,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914972\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1196",
            "503006",
            "202212",
            "2022",
            "0.00",
            "53916062.37",
            "0.00"
          ],
          "rowNumber": 2914972,
          "rowPosition": 2914973,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914973\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1185",
            "503006",
            "202212",
            "2022",
            "0.00",
            "161537074.04",
            "0.00"
          ],
          "rowNumber": 2914973,
          "rowPosition": 2914974,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914974\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1010",
            "504001",
            "202212",
            "2022",
            "163273486.32",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914974,
          "rowPosition": 2914975,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914975\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1012",
            "504001",
            "202212",
            "2022",
            "165352507.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914975,
          "rowPosition": 2914976,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914976\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1014",
            "504001",
            "202212",
            "2022",
            "167012530.77",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914976,
          "rowPosition": 2914977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914977\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "558",
            "2",
            "1016",
            "504001",
            "202212",
            "2022",
            "53371345.52",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914977,
          "rowPosition": 2914978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914978\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "558",
            "2",
            "1018",
            "504001",
            "202212",
            "2022",
            "53916062.37",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914978,
          "rowPosition": 2914979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914979\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "1",
            "2",
            "167",
            "502001",
            "202212",
            "2022",
            "161537074.04",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914979,
          "rowPosition": 2914980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914980\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "1",
            "2",
            "169",
            "502001",
            "202212",
            "2022",
            "52805332.03",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2914980,
          "rowPosition": 2914981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2914981\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 48
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 48,
    "tasks": 1
  },
  "valid": false
}