{
  "version": "4.16.6",
  "time": 25.229,
  "errors": [
    {
      "code": "resource-error",
      "name": "Resource Error",
      "tags": [],
      "note": "Failed to handle a foreign key for resource \"ft_diarias_2024\" as resource \"dm_empenho_desp_2024\" does not exist",
      "message": "The data resource has an error: Failed to handle a foreign key for resource \"ft_diarias_2024\" as resource \"dm_empenho_desp_2024\" does not exist",
      "description": "A validation cannot be processed."
    }
  ],
  "tasks": [],
  "stats": {
    "errors": 1,
    "tasks": 0
  },
  "valid": false
}