{
  "version": "4.16.6",
  "time": 353.579,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_despesa_2023",
        "title": "Despesa 2023",
        "path": "data/ft_despesa_2023.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_categ_econ",
              "title": "Categoria Econômica da Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo",
              "title": "Grupo de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_modalidade_aplic",
              "title": "Modalidade de Aplicação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_subfuncao",
              "title": "Subfunção - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedencia",
              "title": "Procedência - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_documento",
              "title": "Tipo de Documento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "tp_operacao",
              "title": "Tipo Operação - Chave Origem",
              "type": "string",
              "format": "default",
              "constraints": {
                "enum": [
                  "1",
                  "2"
                ]
              }
            },
            {
              "name": "cd_documento",
              "title": "Documento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "cd_evento",
              "title": "Evento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_anomes",
              "title": "Ano e Mês",
              "type": "string",
              "format": "default",
              "bareNumber": true,
              "notes": [
                "O tipo yearmonth somente aceita representação YYYY-MM (ie. com hífen)"
              ]
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_empenhado",
              "title": "Valor Empenhado",
              "description": "Valor do orçamento reservado para fazer face a compromisso formalmente assumido com fornecedor ou credor.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liquidado",
              "title": "Valor Liquidado",
              "description": "Valor que o fornecedor ou credor tem direito a receber referente a produto ou serviço devidamente entregue ou prestado.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_pago",
              "title": "Valor Pago",
              "description": "- > \nValor referente aos pagamentos efetuados através de movimentações bancárias, escriturais e apropriação contábil da\ndespesa. O efetivo pagamento pode estar pendente de transmissão ao banco e/ou sujeito a compensação bancária.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            },
            {
              "fields": [
                "id_tipo_documento"
              ],
              "reference": {
                "fields": [
                  "id_tipo_documento"
                ],
                "resource": "dm_tipo_documento"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_categ_econ"
              ],
              "reference": {
                "fields": [
                  "id_categ_econ"
                ],
                "resource": "dm_categ_econ"
              }
            },
            {
              "fields": [
                "id_grupo"
              ],
              "reference": {
                "fields": [
                  "id_grupo"
                ],
                "resource": "dm_grupo_desp"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_2023"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_subfuncao"
              ],
              "reference": {
                "fields": [
                  "id_subfuncao"
                ],
                "resource": "dm_subfuncao_desp"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_modalidade_aplic"
              ],
              "reference": {
                "fields": [
                  "id_modalidade_aplic"
                ],
                "resource": "dm_modalidade_aplic"
              }
            },
            {
              "fields": [
                "id_procedencia"
              ],
              "reference": {
                "fields": [
                  "id_procedencia"
                ],
                "resource": "dm_procedencia"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_despesa_2023"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "7743bd0a265b7c8cd1688f35adec2374",
          "bytes": 26562225,
          "fields": 24,
          "rows": 1815247
        }
      },
      "time": 353.579,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810954,
          "rowPosition": 1810955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810955\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810955,
          "rowPosition": 1810956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810956\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810957,
          "rowPosition": 1810958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810958\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810958,
          "rowPosition": 1810959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810959\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810960,
          "rowPosition": 1810961,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810961\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810962,
          "rowPosition": 1810963,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810963\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1810966,
          "rowPosition": 1810967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1810967\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811268,
          "rowPosition": 1811269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811269\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811268,
          "rowPosition": 1811269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811269\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811296,
          "rowPosition": 1811297,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811297\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811300,
          "rowPosition": 1811301,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811301\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811306,
          "rowPosition": 1811307,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811307\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811609,
          "rowPosition": 1811610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811610\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811650,
          "rowPosition": 1811651,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811651\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811771,
          "rowPosition": 1811772,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811772\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1811772,
          "rowPosition": 1811773,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1811773\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812010,
          "rowPosition": 1812011,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812011\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812012,
          "rowPosition": 1812013,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812013\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812018,
          "rowPosition": 1812019,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812019\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812019,
          "rowPosition": 1812020,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812020\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812020,
          "rowPosition": 1812021,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812021\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812021,
          "rowPosition": 1812022,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812022\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812022,
          "rowPosition": 1812023,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812023\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812023,
          "rowPosition": 1812024,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812024\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812023,
          "rowPosition": 1812024,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812024\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812024,
          "rowPosition": 1812025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812025\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812025,
          "rowPosition": 1812026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812026\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812025,
          "rowPosition": 1812026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812026\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812026,
          "rowPosition": 1812027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812027\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812026,
          "rowPosition": 1812027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812027\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812027,
          "rowPosition": 1812028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812028\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812027,
          "rowPosition": 1812028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812028\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812028,
          "rowPosition": 1812029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812029\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812029,
          "rowPosition": 1812030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812030\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812030,
          "rowPosition": 1812031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812031\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812031,
          "rowPosition": 1812032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812032\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812032,
          "rowPosition": 1812033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812033\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812033,
          "rowPosition": 1812034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812034\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812034,
          "rowPosition": 1812035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812035\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812034,
          "rowPosition": 1812035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812035\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812035,
          "rowPosition": 1812036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812036\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812036,
          "rowPosition": 1812037,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812037\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812037,
          "rowPosition": 1812038,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812038\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812039,
          "rowPosition": 1812040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812040\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812040,
          "rowPosition": 1812041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812041\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812041,
          "rowPosition": 1812042,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812042\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812042,
          "rowPosition": 1812043,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812043\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812043,
          "rowPosition": 1812044,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812044\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812044,
          "rowPosition": 1812045,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812045\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812045,
          "rowPosition": 1812046,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812046\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812046,
          "rowPosition": 1812047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812047\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812046,
          "rowPosition": 1812047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812047\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812047,
          "rowPosition": 1812048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812048\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812390,
          "rowPosition": 1812391,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812391\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812392,
          "rowPosition": 1812393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812393\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812392,
          "rowPosition": 1812393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812393\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812393,
          "rowPosition": 1812394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812394\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812394,
          "rowPosition": 1812395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812395\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812394,
          "rowPosition": 1812395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812395\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812395,
          "rowPosition": 1812396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812396\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812396,
          "rowPosition": 1812397,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812397\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812404,
          "rowPosition": 1812405,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812405\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812405,
          "rowPosition": 1812406,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812406\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812406,
          "rowPosition": 1812407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812407\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812407,
          "rowPosition": 1812408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812408\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812408,
          "rowPosition": 1812409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812409\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812409,
          "rowPosition": 1812410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812410\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812409,
          "rowPosition": 1812410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812410\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812410,
          "rowPosition": 1812411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812411\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812411,
          "rowPosition": 1812412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812412\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812412,
          "rowPosition": 1812413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812413\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812413,
          "rowPosition": 1812414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812414\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812414,
          "rowPosition": 1812415,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812415\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812416,
          "rowPosition": 1812417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812417\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812416,
          "rowPosition": 1812417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812417\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812417,
          "rowPosition": 1812418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812418\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812417,
          "rowPosition": 1812418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812418\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812418,
          "rowPosition": 1812419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812419\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812419,
          "rowPosition": 1812420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812420\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812419,
          "rowPosition": 1812420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812420\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812420,
          "rowPosition": 1812421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812421\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812420,
          "rowPosition": 1812421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812421\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812421,
          "rowPosition": 1812422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812422\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812422,
          "rowPosition": 1812423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812423\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812423,
          "rowPosition": 1812424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812424\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812424,
          "rowPosition": 1812425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812425\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812425,
          "rowPosition": 1812426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812426\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812425,
          "rowPosition": 1812426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812426\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812426,
          "rowPosition": 1812427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812427\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812427,
          "rowPosition": 1812428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812428\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812427,
          "rowPosition": 1812428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812428\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812428,
          "rowPosition": 1812429,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812429\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812429,
          "rowPosition": 1812430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812430\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812430,
          "rowPosition": 1812431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812431\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812431,
          "rowPosition": 1812432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812432\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812431,
          "rowPosition": 1812432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812432\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812432,
          "rowPosition": 1812433,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812433\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812433,
          "rowPosition": 1812434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812434\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812433,
          "rowPosition": 1812434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812434\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812434,
          "rowPosition": 1812435,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812435\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812435,
          "rowPosition": 1812436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812436\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812435,
          "rowPosition": 1812436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812436\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812436,
          "rowPosition": 1812437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812437\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812437,
          "rowPosition": 1812438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812438\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812438,
          "rowPosition": 1812439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812439\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812438,
          "rowPosition": 1812439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812439\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812439,
          "rowPosition": 1812440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812440\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812440,
          "rowPosition": 1812441,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812441\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812441,
          "rowPosition": 1812442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812442\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812441,
          "rowPosition": 1812442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812442\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812442,
          "rowPosition": 1812443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812443\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812443,
          "rowPosition": 1812444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812444\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812782,
          "rowPosition": 1812783,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812783\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812783,
          "rowPosition": 1812784,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812784\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812784,
          "rowPosition": 1812785,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812785\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812785,
          "rowPosition": 1812786,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812786\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812786,
          "rowPosition": 1812787,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812787\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812787,
          "rowPosition": 1812788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812788\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812787,
          "rowPosition": 1812788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812788\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812788,
          "rowPosition": 1812789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812789\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812789,
          "rowPosition": 1812790,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812790\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1812790,
          "rowPosition": 1812791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1812791\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 122
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 122,
    "tasks": 1
  },
  "valid": false
}